/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AstroAppDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkFeDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkJWKSPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FeAcmCertArn": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Frontend": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "GoApi": {
      "type": "sst.aws.ApiGatewayV1"
      "url": string
    }
    "HostConfigBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ImgproxyUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JobDeadLetter": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "JobQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "JobQueueUrl": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "JobResultBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "JobResultBucketName": {
      "name": string
      "type": "sst.sst.Linkable"
    }
    "JobStatus": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "JobStatusName": {
      "name": string
      "type": "sst.sst.Linkable"
    }
    "NotifySecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SQLDevBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SQLDevRealtimeSST": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "SupabaseKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "sqldevSupabaseVPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
  }
}

import "sst"
export {}