/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AstroAppDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkFeDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkJWKSPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FeAcmCertArn": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Frontend": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "SQLDevRealtimeSST": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "SupabaseKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "sqldevSupabaseVPC": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}