// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for NotifyJSONBodyVisibility.
const (
	Private NotifyJSONBodyVisibility = "private"
	Public  NotifyJSONBodyVisibility = "public"
)

// Valid indicates whether the value is a known member of the NotifyJSONBodyVisibility enum.
func (e NotifyJSONBodyVisibility) Valid() bool {
	switch e {
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// S3Object defines model for S3Object.
type S3Object struct {
	ETag         *string    `json:"eTag,omitempty"`
	Key          *string    `json:"key,omitempty"`
	LastModified *time.Time `json:"lastModified,omitempty"`
	Size         *int       `json:"size,omitempty"`
}

// DeleteObjectsJSONBody defines parameters for DeleteObjects.
type DeleteObjectsJSONBody struct {
	Keys []string `json:"keys"`
}

// DeleteObjectsParams defines parameters for DeleteObjects.
type DeleteObjectsParams struct {
	BypassGovernance *bool `form:"bypassGovernance,omitempty" json:"bypassGovernance,omitempty"`
}

// UploadObjectMultipartBody defines parameters for UploadObject.
type UploadObjectMultipartBody struct {
	// File File binary contents payload.
	File openapi_types.File `json:"file"`
}

// UploadObjectParams defines parameters for UploadObject.
type UploadObjectParams struct {
	// Key The destination S3 key path.
	Key string `form:"key" json:"key"`
}

// CopyObjectJSONBody defines parameters for CopyObject.
type CopyObjectJSONBody struct {
	// DestinationBucket Can be identical to sourceBucket for copy-to-folder actions.
	DestinationBucket string `json:"destinationBucket"`

	// DestinationKey The target object key name or destination folder pattern string.
	DestinationKey string `json:"destinationKey"`
}

// CopyObjectParams defines parameters for CopyObject.
type CopyObjectParams struct {
	// Key The source S3 object key path (may include prefixes/slashes).
	Key string `form:"key" json:"key"`
}

// DownloadObjectParams defines parameters for DownloadObject.
type DownloadObjectParams struct {
	// Key The S3 object key path (may include prefixes/slashes).
	Key string `form:"key" json:"key"`
}

// DeleteSingleObjectParams defines parameters for DeleteSingleObject.
type DeleteSingleObjectParams struct {
	// Key The S3 object key path (may include prefixes/slashes).
	Key              string  `form:"key" json:"key"`
	VersionId        *string `form:"versionId,omitempty" json:"versionId,omitempty"`
	BypassGovernance *bool   `form:"bypassGovernance,omitempty" json:"bypassGovernance,omitempty"`
}

// NotifyJSONBody defines parameters for Notify.
type NotifyJSONBody struct {
	// Message The payload message to be published
	Message string `json:"message"`

	// Recipients Clerk user ids (JWT sub) that should receive the notification. Required when visibility is private; ignored when public.
	Recipients *[]string `json:"recipients,omitempty"`

	// View The view identifier used to construct the IoT topic
	View string `json:"view"`

	// Visibility public publishes once to {app}/{stage}/public/{view}. private publishes once per recipient to {app}/{stage}/user/{clerkUserId}/{view}.
	Visibility NotifyJSONBodyVisibility `json:"visibility"`
}

// NotifyParams defines parameters for Notify.
type NotifyParams struct {
	// XNotifySecret Secret key for authenticating the request
	XNotifySecret string `json:"x-notify-secret"`
}

// NotifyJSONBodyVisibility defines parameters for Notify.
type NotifyJSONBodyVisibility string

// RenderMdJSONBody defines parameters for RenderMd.
type RenderMdJSONBody struct {
	Text string `json:"text"`
}

// DeleteObjectsJSONRequestBody defines body for DeleteObjects for application/json ContentType.
type DeleteObjectsJSONRequestBody DeleteObjectsJSONBody

// UploadObjectMultipartRequestBody defines body for UploadObject for multipart/form-data ContentType.
type UploadObjectMultipartRequestBody UploadObjectMultipartBody

// CopyObjectJSONRequestBody defines body for CopyObject for application/json ContentType.
type CopyObjectJSONRequestBody CopyObjectJSONBody

// NotifyJSONRequestBody defines body for Notify for application/json ContentType.
type NotifyJSONRequestBody NotifyJSONBody

// RenderMdJSONRequestBody defines body for RenderMd for application/json ContentType.
type RenderMdJSONRequestBody RenderMdJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// BucketExists request
	BucketExists(ctx context.Context, bucketName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteObjectsWithBody request with any body
	DeleteObjectsWithBody(ctx context.Context, bucketName string, params *DeleteObjectsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteObjects(ctx context.Context, bucketName string, params *DeleteObjectsParams, body DeleteObjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListObjects request
	ListObjects(ctx context.Context, bucketName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadObjectWithBody request with any body
	UploadObjectWithBody(ctx context.Context, bucketName string, params *UploadObjectParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CopyObjectWithBody request with any body
	CopyObjectWithBody(ctx context.Context, bucketName string, params *CopyObjectParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CopyObject(ctx context.Context, bucketName string, params *CopyObjectParams, body CopyObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadObject request
	DownloadObject(ctx context.Context, bucketName string, params *DownloadObjectParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteSingleObject request
	DeleteSingleObject(ctx context.Context, bucketName string, params *DeleteSingleObjectParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// NotifyWithBody request with any body
	NotifyWithBody(ctx context.Context, params *NotifyParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Notify(ctx context.Context, params *NotifyParams, body NotifyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RenderMdWithBody request with any body
	RenderMdWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RenderMd(ctx context.Context, body RenderMdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) BucketExists(ctx context.Context, bucketName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBucketExistsRequest(c.Server, bucketName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteObjectsWithBody(ctx context.Context, bucketName string, params *DeleteObjectsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteObjectsRequestWithBody(c.Server, bucketName, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteObjects(ctx context.Context, bucketName string, params *DeleteObjectsParams, body DeleteObjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteObjectsRequest(c.Server, bucketName, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListObjects(ctx context.Context, bucketName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListObjectsRequest(c.Server, bucketName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadObjectWithBody(ctx context.Context, bucketName string, params *UploadObjectParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadObjectRequestWithBody(c.Server, bucketName, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CopyObjectWithBody(ctx context.Context, bucketName string, params *CopyObjectParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCopyObjectRequestWithBody(c.Server, bucketName, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CopyObject(ctx context.Context, bucketName string, params *CopyObjectParams, body CopyObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCopyObjectRequest(c.Server, bucketName, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DownloadObject(ctx context.Context, bucketName string, params *DownloadObjectParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadObjectRequest(c.Server, bucketName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteSingleObject(ctx context.Context, bucketName string, params *DeleteSingleObjectParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteSingleObjectRequest(c.Server, bucketName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NotifyWithBody(ctx context.Context, params *NotifyParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNotifyRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Notify(ctx context.Context, params *NotifyParams, body NotifyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNotifyRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RenderMdWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRenderMdRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RenderMd(ctx context.Context, body RenderMdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRenderMdRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewBucketExistsRequest generates requests for BucketExists
func NewBucketExistsRequest(server string, bucketName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucketName", bucketName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/buckets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteObjectsRequest calls the generic DeleteObjects builder with application/json body
func NewDeleteObjectsRequest(server string, bucketName string, params *DeleteObjectsParams, body DeleteObjectsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteObjectsRequestWithBody(server, bucketName, params, "application/json", bodyReader)
}

// NewDeleteObjectsRequestWithBody generates requests for DeleteObjects with any type of body
func NewDeleteObjectsRequestWithBody(server string, bucketName string, params *DeleteObjectsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucketName", bucketName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/buckets/%s/objects", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.BypassGovernance != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "bypassGovernance", *params.BypassGovernance, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListObjectsRequest generates requests for ListObjects
func NewListObjectsRequest(server string, bucketName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucketName", bucketName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/buckets/%s/objects", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUploadObjectRequestWithBody generates requests for UploadObject with any type of body
func NewUploadObjectRequestWithBody(server string, bucketName string, params *UploadObjectParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucketName", bucketName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/buckets/%s/objects", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "key", params.Key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCopyObjectRequest calls the generic CopyObject builder with application/json body
func NewCopyObjectRequest(server string, bucketName string, params *CopyObjectParams, body CopyObjectJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCopyObjectRequestWithBody(server, bucketName, params, "application/json", bodyReader)
}

// NewCopyObjectRequestWithBody generates requests for CopyObject with any type of body
func NewCopyObjectRequestWithBody(server string, bucketName string, params *CopyObjectParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucketName", bucketName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/buckets/%s/objects/copy", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "key", params.Key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDownloadObjectRequest generates requests for DownloadObject
func NewDownloadObjectRequest(server string, bucketName string, params *DownloadObjectParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucketName", bucketName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/buckets/%s/objects/download", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "key", params.Key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteSingleObjectRequest generates requests for DeleteSingleObject
func NewDeleteSingleObjectRequest(server string, bucketName string, params *DeleteSingleObjectParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucketName", bucketName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/buckets/%s/objects/object", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "key", params.Key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.VersionId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "versionId", *params.VersionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.BypassGovernance != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "bypassGovernance", *params.BypassGovernance, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewNotifyRequest calls the generic Notify builder with application/json body
func NewNotifyRequest(server string, params *NotifyParams, body NotifyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewNotifyRequestWithBody(server, params, "application/json", bodyReader)
}

// NewNotifyRequestWithBody generates requests for Notify with any type of body
func NewNotifyRequestWithBody(server string, params *NotifyParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/notify")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "x-notify-secret", params.XNotifySecret, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("x-notify-secret", headerParam0)

	}

	return req, nil
}

// NewRenderMdRequest calls the generic RenderMd builder with application/json body
func NewRenderMdRequest(server string, body RenderMdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRenderMdRequestWithBody(server, "application/json", bodyReader)
}

// NewRenderMdRequestWithBody generates requests for RenderMd with any type of body
func NewRenderMdRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/renderMd")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// BucketExistsWithResponse request
	BucketExistsWithResponse(ctx context.Context, bucketName string, reqEditors ...RequestEditorFn) (*BucketExistsResponse, error)

	// DeleteObjectsWithBodyWithResponse request with any body
	DeleteObjectsWithBodyWithResponse(ctx context.Context, bucketName string, params *DeleteObjectsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteObjectsResponse, error)

	DeleteObjectsWithResponse(ctx context.Context, bucketName string, params *DeleteObjectsParams, body DeleteObjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteObjectsResponse, error)

	// ListObjectsWithResponse request
	ListObjectsWithResponse(ctx context.Context, bucketName string, reqEditors ...RequestEditorFn) (*ListObjectsResponse, error)

	// UploadObjectWithBodyWithResponse request with any body
	UploadObjectWithBodyWithResponse(ctx context.Context, bucketName string, params *UploadObjectParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadObjectResponse, error)

	// CopyObjectWithBodyWithResponse request with any body
	CopyObjectWithBodyWithResponse(ctx context.Context, bucketName string, params *CopyObjectParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CopyObjectResponse, error)

	CopyObjectWithResponse(ctx context.Context, bucketName string, params *CopyObjectParams, body CopyObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*CopyObjectResponse, error)

	// DownloadObjectWithResponse request
	DownloadObjectWithResponse(ctx context.Context, bucketName string, params *DownloadObjectParams, reqEditors ...RequestEditorFn) (*DownloadObjectResponse, error)

	// DeleteSingleObjectWithResponse request
	DeleteSingleObjectWithResponse(ctx context.Context, bucketName string, params *DeleteSingleObjectParams, reqEditors ...RequestEditorFn) (*DeleteSingleObjectResponse, error)

	// NotifyWithBodyWithResponse request with any body
	NotifyWithBodyWithResponse(ctx context.Context, params *NotifyParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NotifyResponse, error)

	NotifyWithResponse(ctx context.Context, params *NotifyParams, body NotifyJSONRequestBody, reqEditors ...RequestEditorFn) (*NotifyResponse, error)

	// RenderMdWithBodyWithResponse request with any body
	RenderMdWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RenderMdResponse, error)

	RenderMdWithResponse(ctx context.Context, body RenderMdJSONRequestBody, reqEditors ...RequestEditorFn) (*RenderMdResponse, error)
}

type BucketExistsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r BucketExistsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BucketExistsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BucketExistsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteObjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteObjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteObjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteObjectsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListObjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]S3Object
}

// Status returns HTTPResponse.Status
func (r ListObjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListObjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListObjectsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UploadObjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadObjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadObjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UploadObjectResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CopyObjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r CopyObjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CopyObjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CopyObjectResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DownloadObjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DownloadObjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadObjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DownloadObjectResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteSingleObjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteSingleObjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteSingleObjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteSingleObjectResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type NotifyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r NotifyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r NotifyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r NotifyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RenderMdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Html *string `json:"html,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r RenderMdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RenderMdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RenderMdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// BucketExistsWithResponse request returning *BucketExistsResponse
func (c *ClientWithResponses) BucketExistsWithResponse(ctx context.Context, bucketName string, reqEditors ...RequestEditorFn) (*BucketExistsResponse, error) {
	rsp, err := c.BucketExists(ctx, bucketName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBucketExistsResponse(rsp)
}

// DeleteObjectsWithBodyWithResponse request with arbitrary body returning *DeleteObjectsResponse
func (c *ClientWithResponses) DeleteObjectsWithBodyWithResponse(ctx context.Context, bucketName string, params *DeleteObjectsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteObjectsResponse, error) {
	rsp, err := c.DeleteObjectsWithBody(ctx, bucketName, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteObjectsResponse(rsp)
}

func (c *ClientWithResponses) DeleteObjectsWithResponse(ctx context.Context, bucketName string, params *DeleteObjectsParams, body DeleteObjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteObjectsResponse, error) {
	rsp, err := c.DeleteObjects(ctx, bucketName, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteObjectsResponse(rsp)
}

// ListObjectsWithResponse request returning *ListObjectsResponse
func (c *ClientWithResponses) ListObjectsWithResponse(ctx context.Context, bucketName string, reqEditors ...RequestEditorFn) (*ListObjectsResponse, error) {
	rsp, err := c.ListObjects(ctx, bucketName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListObjectsResponse(rsp)
}

// UploadObjectWithBodyWithResponse request with arbitrary body returning *UploadObjectResponse
func (c *ClientWithResponses) UploadObjectWithBodyWithResponse(ctx context.Context, bucketName string, params *UploadObjectParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadObjectResponse, error) {
	rsp, err := c.UploadObjectWithBody(ctx, bucketName, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadObjectResponse(rsp)
}

// CopyObjectWithBodyWithResponse request with arbitrary body returning *CopyObjectResponse
func (c *ClientWithResponses) CopyObjectWithBodyWithResponse(ctx context.Context, bucketName string, params *CopyObjectParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CopyObjectResponse, error) {
	rsp, err := c.CopyObjectWithBody(ctx, bucketName, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCopyObjectResponse(rsp)
}

func (c *ClientWithResponses) CopyObjectWithResponse(ctx context.Context, bucketName string, params *CopyObjectParams, body CopyObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*CopyObjectResponse, error) {
	rsp, err := c.CopyObject(ctx, bucketName, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCopyObjectResponse(rsp)
}

// DownloadObjectWithResponse request returning *DownloadObjectResponse
func (c *ClientWithResponses) DownloadObjectWithResponse(ctx context.Context, bucketName string, params *DownloadObjectParams, reqEditors ...RequestEditorFn) (*DownloadObjectResponse, error) {
	rsp, err := c.DownloadObject(ctx, bucketName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadObjectResponse(rsp)
}

// DeleteSingleObjectWithResponse request returning *DeleteSingleObjectResponse
func (c *ClientWithResponses) DeleteSingleObjectWithResponse(ctx context.Context, bucketName string, params *DeleteSingleObjectParams, reqEditors ...RequestEditorFn) (*DeleteSingleObjectResponse, error) {
	rsp, err := c.DeleteSingleObject(ctx, bucketName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteSingleObjectResponse(rsp)
}

// NotifyWithBodyWithResponse request with arbitrary body returning *NotifyResponse
func (c *ClientWithResponses) NotifyWithBodyWithResponse(ctx context.Context, params *NotifyParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NotifyResponse, error) {
	rsp, err := c.NotifyWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNotifyResponse(rsp)
}

func (c *ClientWithResponses) NotifyWithResponse(ctx context.Context, params *NotifyParams, body NotifyJSONRequestBody, reqEditors ...RequestEditorFn) (*NotifyResponse, error) {
	rsp, err := c.Notify(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNotifyResponse(rsp)
}

// RenderMdWithBodyWithResponse request with arbitrary body returning *RenderMdResponse
func (c *ClientWithResponses) RenderMdWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RenderMdResponse, error) {
	rsp, err := c.RenderMdWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRenderMdResponse(rsp)
}

func (c *ClientWithResponses) RenderMdWithResponse(ctx context.Context, body RenderMdJSONRequestBody, reqEditors ...RequestEditorFn) (*RenderMdResponse, error) {
	rsp, err := c.RenderMd(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRenderMdResponse(rsp)
}

// ParseBucketExistsResponse parses an HTTP response from a BucketExistsWithResponse call
func ParseBucketExistsResponse(rsp *http.Response) (*BucketExistsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BucketExistsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDeleteObjectsResponse parses an HTTP response from a DeleteObjectsWithResponse call
func ParseDeleteObjectsResponse(rsp *http.Response) (*DeleteObjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteObjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListObjectsResponse parses an HTTP response from a ListObjectsWithResponse call
func ParseListObjectsResponse(rsp *http.Response) (*ListObjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListObjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []S3Object
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUploadObjectResponse parses an HTTP response from a UploadObjectWithResponse call
func ParseUploadObjectResponse(rsp *http.Response) (*UploadObjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadObjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCopyObjectResponse parses an HTTP response from a CopyObjectWithResponse call
func ParseCopyObjectResponse(rsp *http.Response) (*CopyObjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CopyObjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDownloadObjectResponse parses an HTTP response from a DownloadObjectWithResponse call
func ParseDownloadObjectResponse(rsp *http.Response) (*DownloadObjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadObjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDeleteSingleObjectResponse parses an HTTP response from a DeleteSingleObjectWithResponse call
func ParseDeleteSingleObjectResponse(rsp *http.Response) (*DeleteSingleObjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteSingleObjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseNotifyResponse parses an HTTP response from a NotifyWithResponse call
func ParseNotifyResponse(rsp *http.Response) (*NotifyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &NotifyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseRenderMdResponse parses an HTTP response from a RenderMdWithResponse call
func ParseRenderMdResponse(rsp *http.Response) (*RenderMdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RenderMdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Html *string `json:"html,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check Bucket Existence
	// (GET /buckets/{bucketName})
	BucketExists(w http.ResponseWriter, r *http.Request, bucketName string)
	// Batch Delete Objects
	// (DELETE /buckets/{bucketName}/objects)
	DeleteObjects(w http.ResponseWriter, r *http.Request, bucketName string, params DeleteObjectsParams)
	// List Objects in a Bucket
	// (GET /buckets/{bucketName}/objects)
	ListObjects(w http.ResponseWriter, r *http.Request, bucketName string)
	// Upload Object (Standard or Large)
	// (POST /buckets/{bucketName}/objects)
	UploadObject(w http.ResponseWriter, r *http.Request, bucketName string, params UploadObjectParams)
	// Copy Object
	// (POST /buckets/{bucketName}/objects/copy)
	CopyObject(w http.ResponseWriter, r *http.Request, bucketName string, params CopyObjectParams)
	// Download Object
	// (GET /buckets/{bucketName}/objects/download)
	DownloadObject(w http.ResponseWriter, r *http.Request, bucketName string, params DownloadObjectParams)
	// Delete Single Object
	// (DELETE /buckets/{bucketName}/objects/object)
	DeleteSingleObject(w http.ResponseWriter, r *http.Request, bucketName string, params DeleteSingleObjectParams)
	// Send a notification to an IoT topic
	// (POST /notify)
	Notify(w http.ResponseWriter, r *http.Request, params NotifyParams)
	// Render Markdown to HTML
	// (POST /renderMd)
	RenderMd(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// BucketExists operation middleware
func (siw *ServerInterfaceWrapper) BucketExists(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "bucketName" -------------
	var bucketName string

	err = runtime.BindStyledParameterWithOptions("simple", "bucketName", mux.Vars(r)["bucketName"], &bucketName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucketName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BucketExists(w, r, bucketName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteObjects operation middleware
func (siw *ServerInterfaceWrapper) DeleteObjects(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "bucketName" -------------
	var bucketName string

	err = runtime.BindStyledParameterWithOptions("simple", "bucketName", mux.Vars(r)["bucketName"], &bucketName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucketName", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteObjectsParams

	// ------------- Optional query parameter "bypassGovernance" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "bypassGovernance", r.URL.Query(), &params.BypassGovernance, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "bypassGovernance"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bypassGovernance", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteObjects(w, r, bucketName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListObjects operation middleware
func (siw *ServerInterfaceWrapper) ListObjects(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "bucketName" -------------
	var bucketName string

	err = runtime.BindStyledParameterWithOptions("simple", "bucketName", mux.Vars(r)["bucketName"], &bucketName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucketName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListObjects(w, r, bucketName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadObject operation middleware
func (siw *ServerInterfaceWrapper) UploadObject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "bucketName" -------------
	var bucketName string

	err = runtime.BindStyledParameterWithOptions("simple", "bucketName", mux.Vars(r)["bucketName"], &bucketName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucketName", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadObjectParams

	// ------------- Required query parameter "key" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "key", r.URL.Query(), &params.Key, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "key"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadObject(w, r, bucketName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CopyObject operation middleware
func (siw *ServerInterfaceWrapper) CopyObject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "bucketName" -------------
	var bucketName string

	err = runtime.BindStyledParameterWithOptions("simple", "bucketName", mux.Vars(r)["bucketName"], &bucketName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucketName", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CopyObjectParams

	// ------------- Required query parameter "key" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "key", r.URL.Query(), &params.Key, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "key"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CopyObject(w, r, bucketName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadObject operation middleware
func (siw *ServerInterfaceWrapper) DownloadObject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "bucketName" -------------
	var bucketName string

	err = runtime.BindStyledParameterWithOptions("simple", "bucketName", mux.Vars(r)["bucketName"], &bucketName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucketName", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadObjectParams

	// ------------- Required query parameter "key" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "key", r.URL.Query(), &params.Key, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "key"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadObject(w, r, bucketName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSingleObject operation middleware
func (siw *ServerInterfaceWrapper) DeleteSingleObject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "bucketName" -------------
	var bucketName string

	err = runtime.BindStyledParameterWithOptions("simple", "bucketName", mux.Vars(r)["bucketName"], &bucketName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucketName", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteSingleObjectParams

	// ------------- Required query parameter "key" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "key", r.URL.Query(), &params.Key, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "key"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "versionId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "versionId", r.URL.Query(), &params.VersionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "versionId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "versionId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "bypassGovernance" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "bypassGovernance", r.URL.Query(), &params.BypassGovernance, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "bypassGovernance"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bypassGovernance", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSingleObject(w, r, bucketName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Notify operation middleware
func (siw *ServerInterfaceWrapper) Notify(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params NotifyParams

	headers := r.Header

	// ------------- Required header parameter "x-notify-secret" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-notify-secret")]; found {
		var XNotifySecret string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-notify-secret", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-notify-secret", valueList[0], &XNotifySecret, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-notify-secret", Err: err})
			return
		}

		params.XNotifySecret = XNotifySecret

	} else {
		err = fmt.Errorf("Header parameter x-notify-secret is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-notify-secret", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Notify(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenderMd operation middleware
func (siw *ServerInterfaceWrapper) RenderMd(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenderMd(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/buckets/{bucketName}", wrapper.BucketExists).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/buckets/{bucketName}/objects", wrapper.DeleteObjects).Methods(http.MethodDelete)

	r.HandleFunc(options.BaseURL+"/buckets/{bucketName}/objects", wrapper.ListObjects).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/buckets/{bucketName}/objects", wrapper.UploadObject).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/buckets/{bucketName}/objects/copy", wrapper.CopyObject).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/buckets/{bucketName}/objects/download", wrapper.DownloadObject).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/buckets/{bucketName}/objects/object", wrapper.DeleteSingleObject).Methods(http.MethodDelete)

	r.HandleFunc(options.BaseURL+"/notify", wrapper.Notify).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/renderMd", wrapper.RenderMd).Methods(http.MethodPost)

	return r
}

type BucketExistsRequestObject struct {
	BucketName string `json:"bucketName"`
}

type BucketExistsResponseObject interface {
	VisitBucketExistsResponse(w http.ResponseWriter) error
}

type BucketExists200Response struct {
}

func (response BucketExists200Response) VisitBucketExistsResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type BucketExists404Response struct {
}

func (response BucketExists404Response) VisitBucketExistsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type DeleteObjectsRequestObject struct {
	BucketName string `json:"bucketName"`
	Params     DeleteObjectsParams
	Body       *DeleteObjectsJSONRequestBody
}

type DeleteObjectsResponseObject interface {
	VisitDeleteObjectsResponse(w http.ResponseWriter) error
}

type DeleteObjects200Response struct {
}

func (response DeleteObjects200Response) VisitDeleteObjectsResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteObjects404Response struct {
}

func (response DeleteObjects404Response) VisitDeleteObjectsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListObjectsRequestObject struct {
	BucketName string `json:"bucketName"`
}

type ListObjectsResponseObject interface {
	VisitListObjectsResponse(w http.ResponseWriter) error
}

type ListObjects200JSONResponse []S3Object

func (response ListObjects200JSONResponse) VisitListObjectsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListObjects404Response struct {
}

func (response ListObjects404Response) VisitListObjectsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UploadObjectRequestObject struct {
	BucketName string `json:"bucketName"`
	Params     UploadObjectParams
	Body       *multipart.Reader
}

type UploadObjectResponseObject interface {
	VisitUploadObjectResponse(w http.ResponseWriter) error
}

type UploadObject200Response struct {
}

func (response UploadObject200Response) VisitUploadObjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UploadObject413Response struct {
}

func (response UploadObject413Response) VisitUploadObjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(413)
	return nil
}

type CopyObjectRequestObject struct {
	BucketName string `json:"bucketName"`
	Params     CopyObjectParams
	Body       *CopyObjectJSONRequestBody
}

type CopyObjectResponseObject interface {
	VisitCopyObjectResponse(w http.ResponseWriter) error
}

type CopyObject200Response struct {
}

func (response CopyObject200Response) VisitCopyObjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type CopyObject409Response struct {
}

func (response CopyObject409Response) VisitCopyObjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type DownloadObjectRequestObject struct {
	BucketName string `json:"bucketName"`
	Params     DownloadObjectParams
}

type DownloadObjectResponseObject interface {
	VisitDownloadObjectResponse(w http.ResponseWriter) error
}

type DownloadObject200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response DownloadObject200ApplicationoctetStreamResponse) VisitDownloadObjectResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadObject404Response struct {
}

func (response DownloadObject404Response) VisitDownloadObjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type DeleteSingleObjectRequestObject struct {
	BucketName string `json:"bucketName"`
	Params     DeleteSingleObjectParams
}

type DeleteSingleObjectResponseObject interface {
	VisitDeleteSingleObjectResponse(w http.ResponseWriter) error
}

type DeleteSingleObject204Response struct {
}

func (response DeleteSingleObject204Response) VisitDeleteSingleObjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSingleObject403Response struct {
}

func (response DeleteSingleObject403Response) VisitDeleteSingleObjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type NotifyRequestObject struct {
	Params NotifyParams
	Body   *NotifyJSONRequestBody
}

type NotifyResponseObject interface {
	VisitNotifyResponse(w http.ResponseWriter) error
}

type Notify200Response struct {
}

func (response Notify200Response) VisitNotifyResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Notify400Response struct {
}

func (response Notify400Response) VisitNotifyResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type Notify401Response struct {
}

func (response Notify401Response) VisitNotifyResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type Notify500Response struct {
}

func (response Notify500Response) VisitNotifyResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type RenderMdRequestObject struct {
	Body *RenderMdJSONRequestBody
}

type RenderMdResponseObject interface {
	VisitRenderMdResponse(w http.ResponseWriter) error
}

type RenderMd200JSONResponse struct {
	Html *string `json:"html,omitempty"`
}

func (response RenderMd200JSONResponse) VisitRenderMdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RenderMd400Response struct {
}

func (response RenderMd400Response) VisitRenderMdResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Check Bucket Existence
	// (GET /buckets/{bucketName})
	BucketExists(ctx context.Context, request BucketExistsRequestObject) (BucketExistsResponseObject, error)
	// Batch Delete Objects
	// (DELETE /buckets/{bucketName}/objects)
	DeleteObjects(ctx context.Context, request DeleteObjectsRequestObject) (DeleteObjectsResponseObject, error)
	// List Objects in a Bucket
	// (GET /buckets/{bucketName}/objects)
	ListObjects(ctx context.Context, request ListObjectsRequestObject) (ListObjectsResponseObject, error)
	// Upload Object (Standard or Large)
	// (POST /buckets/{bucketName}/objects)
	UploadObject(ctx context.Context, request UploadObjectRequestObject) (UploadObjectResponseObject, error)
	// Copy Object
	// (POST /buckets/{bucketName}/objects/copy)
	CopyObject(ctx context.Context, request CopyObjectRequestObject) (CopyObjectResponseObject, error)
	// Download Object
	// (GET /buckets/{bucketName}/objects/download)
	DownloadObject(ctx context.Context, request DownloadObjectRequestObject) (DownloadObjectResponseObject, error)
	// Delete Single Object
	// (DELETE /buckets/{bucketName}/objects/object)
	DeleteSingleObject(ctx context.Context, request DeleteSingleObjectRequestObject) (DeleteSingleObjectResponseObject, error)
	// Send a notification to an IoT topic
	// (POST /notify)
	Notify(ctx context.Context, request NotifyRequestObject) (NotifyResponseObject, error)
	// Render Markdown to HTML
	// (POST /renderMd)
	RenderMd(ctx context.Context, request RenderMdRequestObject) (RenderMdResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// BucketExists operation middleware
func (sh *strictHandler) BucketExists(w http.ResponseWriter, r *http.Request, bucketName string) {
	var request BucketExistsRequestObject

	request.BucketName = bucketName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BucketExists(ctx, request.(BucketExistsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BucketExists")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BucketExistsResponseObject); ok {
		if err := validResponse.VisitBucketExistsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteObjects operation middleware
func (sh *strictHandler) DeleteObjects(w http.ResponseWriter, r *http.Request, bucketName string, params DeleteObjectsParams) {
	var request DeleteObjectsRequestObject

	request.BucketName = bucketName
	request.Params = params

	var body DeleteObjectsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteObjects(ctx, request.(DeleteObjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteObjects")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteObjectsResponseObject); ok {
		if err := validResponse.VisitDeleteObjectsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListObjects operation middleware
func (sh *strictHandler) ListObjects(w http.ResponseWriter, r *http.Request, bucketName string) {
	var request ListObjectsRequestObject

	request.BucketName = bucketName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListObjects(ctx, request.(ListObjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListObjects")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListObjectsResponseObject); ok {
		if err := validResponse.VisitListObjectsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadObject operation middleware
func (sh *strictHandler) UploadObject(w http.ResponseWriter, r *http.Request, bucketName string, params UploadObjectParams) {
	var request UploadObjectRequestObject

	request.BucketName = bucketName
	request.Params = params

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadObject(ctx, request.(UploadObjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadObject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadObjectResponseObject); ok {
		if err := validResponse.VisitUploadObjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CopyObject operation middleware
func (sh *strictHandler) CopyObject(w http.ResponseWriter, r *http.Request, bucketName string, params CopyObjectParams) {
	var request CopyObjectRequestObject

	request.BucketName = bucketName
	request.Params = params

	var body CopyObjectJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CopyObject(ctx, request.(CopyObjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CopyObject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CopyObjectResponseObject); ok {
		if err := validResponse.VisitCopyObjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadObject operation middleware
func (sh *strictHandler) DownloadObject(w http.ResponseWriter, r *http.Request, bucketName string, params DownloadObjectParams) {
	var request DownloadObjectRequestObject

	request.BucketName = bucketName
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadObject(ctx, request.(DownloadObjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadObject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadObjectResponseObject); ok {
		if err := validResponse.VisitDownloadObjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSingleObject operation middleware
func (sh *strictHandler) DeleteSingleObject(w http.ResponseWriter, r *http.Request, bucketName string, params DeleteSingleObjectParams) {
	var request DeleteSingleObjectRequestObject

	request.BucketName = bucketName
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSingleObject(ctx, request.(DeleteSingleObjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSingleObject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSingleObjectResponseObject); ok {
		if err := validResponse.VisitDeleteSingleObjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Notify operation middleware
func (sh *strictHandler) Notify(w http.ResponseWriter, r *http.Request, params NotifyParams) {
	var request NotifyRequestObject

	request.Params = params

	var body NotifyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Notify(ctx, request.(NotifyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Notify")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(NotifyResponseObject); ok {
		if err := validResponse.VisitNotifyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RenderMd operation middleware
func (sh *strictHandler) RenderMd(w http.ResponseWriter, r *http.Request) {
	var request RenderMdRequestObject

	var body RenderMdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RenderMd(ctx, request.(RenderMdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RenderMd")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RenderMdResponseObject); ok {
		if err := validResponse.VisitRenderMdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FlNc9s4Ev0rXZytmrhKlmQrs5n1nvIdTz4mFXkmhyRVhoCmiBgEGACUrbj037caAGlSotbJbjI5zMmy",
	"ADTQ3a8fHlrXGTdlZTRq77KT68zxAksWPs5nvy8+Ivf0ubKmQuslhhE8Y8vw94qVlcLsJHuf3ZsiHt2b",
	"/br45+L4CI/5r+zuLJ+xX9hiioj3jt5n2Sjz64pmO2+lXmabUXaB676h3CiBduLqRfqUS4Xjj9VyaLVi",
	"zr80QuYSBZnJjS2Zz04ywTweelni0ConP2Nv06Pp8d12ntQel2izzab9ysQwbOgrqXNDiwU6bmXlpdHZ",
	"Sfbm8fwM7r8+BVchl7nkjAagZFUl9RJQi8pI7R0IaZF7tQZvwBcITw3MHz2HP4/hfsk+Gw3zGaRzQV5r",
	"TmbcmLyQPsQnLVgd08y3llUVWto5G2UrtC4e52g8HU/JVVOhZpXMTrJZ+GqUVcwXIYeTRc0v0LvJdfzw",
	"ipW4oYEl+l0HHxbILxxcFugLtMAgLgK8ks47kDp4w2trUXtgnJua/moBMoe1qaFgK4QKbSmdCz7BS1Y5",
	"CsP5g2DqcbB0DhM4d7OHSqL242fIRBw9pxgQBENgT0V2knWXBccsK9GjddnJu+tM0qnJ2WyUaVZS6G78",
	"zEaZxU+1tAQbb2scJdyT41t42Xygya4y2kXwH0+nu/F50AsH+U1Om0sN0o8pE3end/euEgYdaJOWg7Eg",
	"HbAVk4otFI4DFF1dlsyum1RAWhrcR80xTBrM6STC18XtFXrcPchra5aWlSXzkjOl1hAnOihr5SWBMQEb",
	"BVzg2kFuTQkMnNRLhQ0YuNEer3wntY+CmUgjW7ntD+2mtzf+PfM7SsY+1WjXHWvrijn31KzQakYB7toQ",
	"mLNa+ewkZ8phSxQLYxQy3YDmU43OPzAiUFwIjg6lxapKJYqYfHSUgOuO7T7VUrR7ZPUukyVb4rjSRInC",
	"8MM0dEhc+mGUSY+lG3C0PSWzlq0DXm6C9C5u9GGQ8/qx3HxJPcxrztG5vCYw4RXy2qMIHOG8rbmvLVMR",
	"ZMSTKVT7C+WM2SX6BmdUKrmptdgujQfM8wIicqCBzmY0TGkvQqnSkVKBNPSl1uC8sSjgUvpCasJ5i/54",
	"hA7EycwgwDsDfx4PALwz/gPo64vh2MLpHxbz7CT7aXIjGCZJLUxaqbCLss1oK+7JZ1DEXAJcBylfyZTb",
	"6aeINmmHkLe4jKxWxg1g4I9KGSYcMCCZkZgSKramrym989kYXltDJ0QHrmRKhakOVpLB6zplkDi7YFrQ",
	"AC9qfYGC2DACiq8hNxYUYdjCwgiJ3esvnuGJVHhOZtL/L2h2NH4Od2izkmm2RDuO42gPdiEVh1Iqvi9l",
	"btVngSDQeamj8JnP6JoA2oxOOcSvxFZfjeN9jBqvKWb9hCTgoWCe/TdSpQzugoFSAAupmV1Dsu0aLJAX",
	"rbqMc3al5Rajhl2+GaMmoNUx+yJojBXayEqEj7dMerQD9XQ027X2WHvpSYWaiMvtUopISsUEd+aeacGs",
	"IIAGZB7crjcm3FQhT8Ol99BUEkkqJfptyDbcEaxEiPofXMU40r4WI02hA+mB7mWQ2htgICQhj/seBH33",
	"yuiU20NTrc/Mk2A8Flz8Zq/OpOF9JbVbBc7UlreKiLDeFsD3K7206XzWxLIpPrhTsjVIzVUtECqLubxC",
	"N3GKuQLdwV9Sm1+jdjoJTNS9ixumYYEgBeogVimp0f90RxDXEvQOvTlMGGKdd9S2KOps+Tw+Rnfjm7DU",
	"CS4FisDTRVzarGLeo9UQtxjfShO7Pu8c6puRCGEZrKm91JhkGZ2cbnTSTOn+/deAnosIM3YrFtzoXC7r",
	"WC6A1hoLd3C8HIPUFPUVgpdoQckc+ZorDCuU5P5g511DZ2tkxK3kIsylJora+2J9g95KXPUoprmaKXHN",
	"Qzy+ZMKVpUyEafcBk7a5uZ6bb/Zf0M0MuqLhOa7Daw5CiUHLH+BMU48iXZcuRS5SvGs7HwdwaexF4MfQ",
	"Y3jKPF6yNYSmA10DS2OlUmxS1lex6mOGl+P3evdZlQ73g0TCj6WoL5bBhnv0h85bZGWfr24XAXsEb6sq",
	"uxc05Oh5gWK/8H1laEERwhW7C9t102T0y2vHtG29ff2AN1iafumk5lKHAQieENpaaMdwXylz6cAEC6GF",
	"EN9Ma6mXwOA8rT8V5wmyzbs6SC1rFDjPfO0gV2zp9rQQ9ncQ9jYQ5qFD8XdD+56eRpuE7Mc0RHr1d3ev",
	"xi2ZJZbOw/2aWgSmr2xTg6opnAGFez9MhkeoJe40ClKLIIKjVzjaeJn3ZGsfVa/i+C1KcI7cYsw6ecFq",
	"X0S5QrQcJG7SS02+C6T74ibYV4fxIIcuWPqr1BgTQsYCft3RZSmnfalWonNsicOCqeG6NIkKeYFQ1Qsl",
	"XYFiSIdZ5LKSzc8QW7JFob2A2pHkFw7u/Pb2DFy9OABfMA+uMLUSYJFj0BsFQgiebG7zNyl0cFmghpV0",
	"ciEVPX+kg8rKFfP4b5BLbdo54aQ83p9f2k8bZSuJl8PxoJEkWXOSQ7XD0F7gRsd+WDj1qTkDbyrJh+Jz",
	"c+zdLeJx2/g6MESs3sA1q6rN5Np5tsTNJE6bXNNpNuPG9e1lFdJbKyVj1whlYXLNKSN/OLSnYtMYDNFC",
	"XZekauNeVCdxl46G3aODQ/RGLa56Hn+fvmSLx13MRFoZavQzEfCEzo+BUvvb/PdXLd6lA6lXTEkRX6wJ",
	"dzeVA8wihN9A6GkQNjkaaEtpYgxj5WcUcZeftwjhZ4iMQTsmc+F3A82NJWEbbP8y5MAp3deaKZijpTf0",
	"Y9LsY3jCpIqYDI7M52dgMb6r3Ajuv533pf6Idkvxa7GbUrdNtnPUAlgvvrQP0x3AB+61qAXal2J/0+CM",
	"XVAMww1BL4D0yAqSwqKvrXaJXckSCnh29vLFrjR402z0rd6tHq98/3fMn+AZKmXgrbFK3PoGDOv/D5D/",
	"j8cufKm2fsetp9MZL47CX+y4EAcmzcigRwOn76fvZZO2Nj8D3d9BzMaaSsmChRHrbZTFnEK7hTch+XSM",
	"zX8CAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
