// Generated by Cypress Author on 2026-09-22

// Hold the real response so a second submit, fired while the first is still
// in flight, shows up as another match on the same alias.
function delayMutation(method: "POST" | "PATCH", url: string, alias: string) {
  cy.intercept({ method, url }, (req) => {
    req.continue((res) => {
      res.setDelay(1000);
    });
  }).as(alias);
}

function signIn() {
  cy.signInAsUser(0);
}

function ownerId() {
  return cy
    .env<{ test_users: [Cypress.TestUser, Cypress.TestUser] }>(["test_users"])
    .then(({ test_users }) => {
      const owner = test_users[0];
      if (!owner) {
        throw new Error("test_users[0] is missing");
      }
      return owner.user_id;
    });
}

describe("double submit", () => {
  beforeEach(() => {
    cy.viewport("iphone-6");
  });

  it("presses Enter then Submit on a new post → one create request", () => {
    cy.uniqueRecordName("post").then((postText) => {

    signIn();

    cy.intercept("GET", "/api/views/igPosts/list/get").as("listGet");
    cy.visit("/instagreg");
    cy.waitForClerkLoaded();
    cy.get("[data-cy='igPosts_list']", { timeout: 20000 }).should("exist");
    cy.wait("@listGet");

    delayMutation("POST", "/api/views/igPosts/new/item", "createPost");

    // Enter submits the text field. The follow-up click is forced because the
    // submit button is disabled while that request is still in flight, and
    // Cypress would otherwise retry the click until the form resets.
    cy.get("[data-cy='p_text_content_field'] > input", { timeout: 20000 }).type(
      `${postText}{enter}`,
    );
    cy.get("[data-cy='create_ig_post_submit']").click({ force: true });

      cy.wait("@createPost").its("response.statusCode").should("eq", 202);
      cy.get("@createPost.all").should("have.length", 1);
    });
  });

  it("presses Save twice on an edit post → one patch request", () => {
    cy.uniqueRecordName("post").then((postText) => {

    signIn();

    ownerId()
      .then((identifier) => {
        return cy.task("createIgPostAsUser", {
          identifier,
          p_text_content: postText,
          p_public: true,
        });
      })
      .then(() => {
        cy.intercept("GET", "/api/views/igPosts/list/get").as("listGet");
        cy.visit("/instagreg");
      });

    cy.waitForClerkLoaded();
    cy.get("[data-cy='igPosts_list']", { timeout: 20000 }).should("exist");
    cy.wait("@listGet");

    cy.contains("[data-cy='igPosts_list'] article", postText, {
      timeout: 20000,
    })
      .find("[data-cy='ig_post_actions']")
      .click();
    cy.get("[data-cy='ig_post_edit']").click();

    cy.get("[data-cy='edit_p_text_content_field'] textarea", { timeout: 20000 })
      .should("have.value", postText)
      .clear()
      .type(`edited-${postText}`);

    delayMutation("PATCH", "/api/views/igPosts/one/patch", "updatePost");

    // Enter in the textarea inserts a newline, and the pending fallback
    // unmounts the form, so a second click cannot overlap the patch. Two
    // requestSubmit calls in one turn can.
    cy.get("[data-cy='edit_ig_post_form']").then(($form) => {
      const form = $form.get(0);
      const view = form?.ownerDocument?.defaultView;
      // The node is the app iframe's HTMLFormElement. The spec frame's
      // HTMLFormElement is a different constructor, so instanceof fails there.
      if (!view || !(form instanceof view.HTMLFormElement)) {
        throw new Error("edit_ig_post_form is not a form element");
      }
      form.requestSubmit();
      form.requestSubmit();
    });

      cy.wait("@updatePost").its("response.statusCode").should("eq", 202);
      cy.get("@updatePost.all").should("have.length", 1);
    });
  });

  it("presses Enter then Submit on a new todo space → one create request", () => {
    cy.uniqueRecordName("space").then((spaceName) => {

    signIn();

    cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listGet");
    cy.visit("/todos");
    cy.waitForClerkLoaded();
    cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
      "exist",
    );
    cy.wait("@listGet");

    delayMutation(
      "POST",
      "/api/views/tdsTodoSpaces/new/item",
      "createSpace",
    );

    cy.get("[data-cy='p_name_field'] > input", { timeout: 20000 }).type(
      `${spaceName}{enter}`,
    );
    cy.get("[data-cy='create_tds_todo_space_submit']").click({ force: true });

      cy.wait("@createSpace").its("response.statusCode").should("eq", 202);
      cy.get("@createSpace.all").should("have.length", 1);
    });
  });

  it("presses Enter then Submit on a new todo → one create request", () => {
    cy.uniqueRecordName("todo").then((title) => {

    signIn();

    ownerId()
      .then((identifier) => {
        return cy.task("createTdsTodoSpaceAsUser", {
          identifier,
          p_name: `${title}-space`,
          p_public: false,
        });
      })
      .then(({ todo_space_id }) => {
        cy.visit(`/todos/space/${todo_space_id}`);
      });

    cy.waitForClerkLoaded();
    // client-render-time is set when the island hydrator returns, while the
    // server-rendered button still has no React props. A click then does not
    // open the dialog. Wait until this button instance is hydrated.
    cy.get("[data-cy='new_tds_todo_button']", { timeout: 20000 }).should(
      ($btn) => {
        const hydrated = [...$btn].some((el) =>
          Object.getOwnPropertyNames(el).some((name) =>
            name.startsWith("__react"),
          ),
        );
        expect(hydrated, "hydrated new todo button").to.eq(true);
      },
    );

    delayMutation("POST", "/api/views/tdsTodos/*/new/post", "createTodo");

    cy.get("[data-cy='new_tds_todo_button']").click();
    cy.get("[data-cy='p_title_field'] > input", { timeout: 20000 }).type(
      `${title}{enter}`,
    );
    cy.get("[data-cy='create_tds_todo_submit']").click({ force: true });

      cy.wait("@createTodo").its("response.statusCode").should("eq", 202);
      cy.get("@createTodo.all").should("have.length", 1);
    });
  });
});
