// Generated by Cypress Author on 2026-09-16

import { isRecord } from "../tasks/narrow.js";
import { jobIdFrom, waitForJob } from "../support/jobs.js";
import { rememberPreparedObject } from "../support/preparedObject.js";

// Ordered smallest to largest so a failing upload pins down the size threshold.
const TEST_FILES = [
  "cypress/fixtures/testFiles/WIN_20251119_00_55_14_Pro.mp4",
  "cypress/fixtures/testFiles/WIN_20260102_21_30_21_Pro.jpg",
  "cypress/fixtures/testFiles/WIN_20260203_23_03_27_Pro.jpg",
  "cypress/fixtures/testFiles/WIN_20251119_00_55_32_Pro.mp4",
] as const;

const DOWNLOAD_SOURCE =
  "cypress/fixtures/testFiles/WIN_20260102_21_30_21_Pro.jpg";

function fileNameOf(path: string) {
  return path.slice(path.lastIndexOf("/") + 1);
}

function uploadedName(file: Cypress.FileReference): string {
  if (typeof file === "string") {
    return fileNameOf(file);
  }
  if (
    typeof file === "object" &&
    file !== null &&
    "fileName" in file &&
    typeof file.fileName === "string" &&
    file.fileName.length > 0
  ) {
    return file.fileName;
  }
  throw new Error("uploaded fixture is missing a file name");
}

function bucketNameFrom(url: string): string {
  const match = url.match(/\/api\/storage\/buckets\/([^/]+)\/objects/);
  if (!match?.[1]) {
    throw new Error("storage request is missing a bucket");
  }
  return decodeURIComponent(match[1]);
}

function namedFixture(
  path: string,
  marker: string,
): { contents: string; fileName: string } {
  const base = fileNameOf(path);
  const dot = base.lastIndexOf(".");
  const stem = dot >= 0 ? base.slice(0, dot) : base;
  const ext = dot >= 0 ? base.slice(dot) : "";
  return { contents: path, fileName: `${stem}-${marker}${ext}` };
}

function objectsGrid() {
  return cy.get("[data-cy='dStorage_objects']:visible", { timeout: 20000 });
}

function previewRequests(
  interceptions: ReadonlyArray<{ request: { body?: unknown } }>,
  preview: string,
  sourceIncludes?: string,
) {
  return interceptions.filter(function (interception) {
    const body: unknown = interception.request.body;
    if (!isRecord(body) || body.preview !== preview) {
      return false;
    }
    if (!sourceIncludes) {
      return true;
    }
    return (
      typeof body.sourceKey === "string" &&
      body.sourceKey.includes(sourceIncludes)
    );
  });
}

function tileColumnCount(element: HTMLElement): number {
  return getComputedStyle(element)
    .gridTemplateColumns.split(" ")
    .filter((column) => column.trim().length > 0).length;
}

function signInAndOpenDrive() {
  cy.signInAsUser(0);

  cy.intercept({
    method: "GET",
    url: /\/api\/storage\/buckets\/[^/]+\/objects\?/,
  }).as("listObjects");
  // Register once per visit so later waits cannot match an earlier upload.
  cy.intercept({
    method: "POST",
    url: /\/api\/storage\/buckets\/[^/]+\/objects\/presign(\?|$)/,
  }).as("presignObject");
  cy.intercept({
    method: "POST",
    url: /\/api\/storage\/buckets\/[^/]+\/objects\/commit$/,
  }).as("commitObject");

  cy.visit("/drive/mine");
  cy.waitForClerkLoaded();
  objectsGrid().should("exist");
  cy.wait("@listObjects");
}

function fillUploadDialog(files: ReadonlyArray<Cypress.FileReference>) {
  cy.get("[data-cy='dStorage_upload']").click();
  cy.get("[role='dialog'] input[type='file']").selectFile([...files], {
    force: true,
  });
  cy.get("[data-cy='dStorage_upload_submit']").click();
}

function rememberPresign() {
  cy.wait("@presignObject", { timeout: 60000 }).then((interception) => {
    expect(interception.response?.statusCode).to.eq(202);
    return waitForJob(jobIdFrom(interception.response?.body)).then((job) => {
      expect(job.status).to.eq("completed");
      return rememberPreparedObject(job.result);
    });
  });
}

function waitForAccepted(alias: `@${string}`) {
  cy.wait(alias, { timeout: 60000 }).then((interception) => {
    expect(interception.response?.statusCode).to.eq(202);
    return waitForJob(jobIdFrom(interception.response?.body)).then((job) => {
      expect(job.status).to.eq("completed");
    });
  });
}

function uploadThroughDialog(files: readonly Cypress.FileReference[]) {
  fillUploadDialog(files);

  // Direct-to-S3: small presign, then the browser PUTs the bytes.
  // Commits run only after every PUT in the batch has finished.
  for (let i = 0; i < files.length; i++) {
    rememberPresign();
  }
  for (let i = 0; i < files.length; i++) {
    waitForAccepted("@commitObject");
  }

  cy.get("[role='dialog']", { timeout: 20000 }).should("not.exist");
  // Wait for the list refetch before reading a row.
  cy.wait("@listObjects", { timeout: 20000 });

  for (const file of files) {
    objectsGrid().should("contain", uploadedName(file));
  }
}

describe("drive", () => {
  beforeEach(() => {
    cy.viewport("iphone-6");
  });

  it("uploads each test file one at a time → each name appears in the storage table", () => {
    cy.uniqueRecordName("one").then((marker) => {
      signInAndOpenDrive();

      for (const path of TEST_FILES) {
        uploadThroughDialog([namedFixture(path, marker)]);
      }
    });
  });

  // Generated by Cypress Author on 2026-10-06
  // The four size boundaries are covered one at a time. The batch only needs
  // two small fixtures so the largest file is not transferred twice.
  it("uploads two small files together → both names appear in the storage table", () => {
    cy.uniqueRecordName("batch").then((marker) => {
      signInAndOpenDrive();
      uploadThroughDialog(TEST_FILES.slice(0, 2).map((path) => namedFixture(path, marker)));
    });
  });

  it("downloads a stored file from the row actions menu → saved bytes match the original", () => {
    cy.uniqueRecordName("download").then((marker) => {
      const file = namedFixture(DOWNLOAD_SOURCE, marker);

      signInAndOpenDrive();
      uploadThroughDialog([file]);

    cy.intercept({
      method: "GET",
      url: /\/api\/storage\/buckets\/[^/]+\/objects\/download/,
    }).as("downloadObject");

      objectsGrid()
        .contains("[data-cy='dStorage_item']", file.fileName)
        .find(`button[aria-label="Actions for ${file.fileName}"]`)
        .click();
      cy.get("[data-cy='dStorage_download']").click();

      cy.wait("@downloadObject", { timeout: 20000 }).then((interception) => {
        expect(interception.response?.statusCode).to.eq(202);
        return waitForJob(jobIdFrom(interception.response?.body)).then((job) => {
          expect(job.status).to.eq("completed");
        });
      });

      cy.readFile(DOWNLOAD_SOURCE, null).then((expected) => {
        cy.readFile(
          `${Cypress.config("downloadsFolder")}/${file.fileName}`,
          null,
          { timeout: 20000 },
        ).should((actual) => {
          expect(
            Cypress.Buffer.from(actual).equals(Cypress.Buffer.from(expected)),
            "downloaded bytes match the original",
          ).to.eq(true);
        });
      });
    });
  });

  // Generated by Cypress Author on 2026-10-07
  it("requests storage without a session → the API rejects the request", () => {
    cy.request({
      method: "GET",
      url: "/api/storage/buckets/not-a-bucket/objects?tab=mine",
      failOnStatusCode: false,
    })
      .its("status")
      .should("eq", 401);
  });

  // Generated by Cypress Author on 2026-10-07
  it("requests another bucket → the API refuses the request", () => {
    signInAndOpenDrive();
    cy.request({
      method: "GET",
      url: "/api/storage/buckets/not-the-linked-bucket/objects?tab=mine",
      failOnStatusCode: false,
    })
      .its("status")
      .should("eq", 403);
  });

  // Generated by Cypress Author on 2026-10-07
  it("deletes a stored file → the file can no longer be downloaded", () => {
    cy.uniqueRecordName("delete-api").then((marker) => {
      const file = namedFixture(DOWNLOAD_SOURCE, marker);
      signInAndOpenDrive();
      fillUploadDialog([file]);

      cy.wait("@presignObject", { timeout: 60000 }).then((interception) => {
        expect(interception.response?.statusCode).to.eq(202);
        return waitForJob(jobIdFrom(interception.response?.body)).then((job) => {
          expect(job.status).to.eq("completed");
          const body = job.result;
          if (!isRecord(body) || typeof body.key !== "string") {
            throw new Error("presign response is missing key");
          }
          const bucket = bucketNameFrom(interception.request.url);
          cy.wrap({ bucket, key: body.key }).as("storedObject");
          return rememberPreparedObject(body);
        });
      });
      waitForAccepted("@commitObject");

      cy.get("@storedObject").then((stored) => {
        const object = stored as unknown as { bucket: string; key: string };
        cy.request({
          method: "DELETE",
          url: `/api/storage/buckets/${encodeURIComponent(object.bucket)}/objects/object`,
          qs: { key: object.key },
          headers: { "Idempotency-Key": `delete-${object.key}` },
          failOnStatusCode: false,
        }).then((response) => {
          expect(response.status).to.eq(202);
          return waitForJob(jobIdFrom(response.body)).then((job) => {
            expect(job.status).to.eq("completed");
          });
        });
        cy.request({
          method: "GET",
          url: `/api/storage/buckets/${encodeURIComponent(object.bucket)}/objects/download`,
          qs: { key: object.key },
          failOnStatusCode: false,
        }).then((response) => {
          expect(response.status).to.eq(202);
          return waitForJob(jobIdFrom(response.body)).then((job) => {
            expect(job.status).to.eq("failed");
            expect(job.httpStatus).to.eq(404);
          });
        });
      });
    });
  });

  // Generated by Cypress Author on 2026-10-07
  it("aborts a file after it is committed → the file stays in the storage table", () => {
    cy.uniqueRecordName("forged-abort").then((marker) => {
      const file = namedFixture(DOWNLOAD_SOURCE, marker);
      signInAndOpenDrive();
      fillUploadDialog([file]);

      cy.wait("@presignObject", { timeout: 60000 }).then((interception) => {
        expect(interception.response?.statusCode).to.eq(202);
        return waitForJob(jobIdFrom(interception.response?.body)).then((job) => {
          expect(job.status).to.eq("completed");
          const body = job.result;
          if (!isRecord(body) || !isRecord(body.pendingUpload)) {
            throw new Error("presign response is missing pendingUpload");
          }
          const bucket = bucketNameFrom(interception.request.url);
          cy.wrap({
            bucket,
            pendingUpload: { ...body.pendingUpload, isNewObject: true },
          }).as("forgedAbort");
          return rememberPreparedObject(body);
        });
      });
      waitForAccepted("@commitObject");
      cy.wait("@listObjects", { timeout: 20000 });

      cy.get("@forgedAbort").then((stored) => {
        const object = stored as unknown as {
          bucket: string;
          pendingUpload: Record<string, unknown>;
        };
        cy.request({
          method: "POST",
          url: `/api/storage/buckets/${encodeURIComponent(object.bucket)}/objects/abort`,
          body: object.pendingUpload,
          headers: { "Idempotency-Key": `forged-abort-${marker}` },
          failOnStatusCode: false,
        }).then((response) => {
          expect(response.status).to.eq(202);
          return waitForJob(jobIdFrom(response.body)).then((job) => {
            expect(job.status).to.eq("completed");
          });
        });
      });

      objectsGrid().should("contain", file.fileName);
    });
  });

  // Generated by Cypress Author on 2026-09-17
  it("S3 upload fails → the object is not committed and does not appear in the storage table", () => {
    cy.uniqueRecordName("fail").then((marker) => {
      const fileName = `upload-should-not-commit-${marker}.jpg`;
      const failedPutPath = "/__cypress_s3_put_fail";

      signInAndOpenDrive();

    cy.intercept({
      method: "POST",
      url: /\/api\/storage\/buckets\/[^/]+\/objects\/abort$/,
    }).as("abortObject");
    // Last-defined route wins: prepare still runs, then the PUT target is
    // rewritten to a same-origin stub so this never depends on AWS hostnames.
    // Later job polls pass through untouched, so a poll the browser cancels on
    // navigation cannot fail the response callback.
    let putTargetRewritten = false;
    cy.intercept("GET", "/api/jobs/*", (req) => {
      if (putTargetRewritten) {
        return;
      }
      req.continue((res) => {
        const body: unknown = res.body;
        if (
          isRecord(body) &&
          isRecord(body.result) &&
          typeof body.result.url === "string"
        ) {
          body.result.url = `${Cypress.config("baseUrl")}${failedPutPath}`;
          putTargetRewritten = true;
        }
      });
    });
    cy.intercept(
      { method: "PUT", url: `**${failedPutPath}` },
      { statusCode: 500, body: "forced upload failure" },
    ).as("s3PutFailed");

    fillUploadDialog([
      {
        contents: DOWNLOAD_SOURCE,
        fileName,
        mimeType: "image/jpeg",
      },
    ]);

      rememberPresign();
    cy.wait("@s3PutFailed", { timeout: 60000 })
      .its("response.statusCode")
      .should("eq", 500);
    cy.wait("@abortObject", { timeout: 60000 }).then((interception) => {
      expect(interception.response?.statusCode).to.eq(202);
      return waitForJob(jobIdFrom(interception.response?.body)).then((job) => {
        expect(job.status).to.eq("completed");
      });
    });
    cy.get("@commitObject.all").should("have.length", 0);

    cy.get("[data-cy='dStorage_upload_error']").should("be.visible");
    cy.get("[role='dialog']").should("exist");

    cy.intercept({
      method: "GET",
      url: /\/api\/storage\/buckets\/[^/]+\/objects\?/,
    }).as("listObjectsAfterFail");
    cy.visit("/drive/mine");
    cy.waitForClerkLoaded();
    objectsGrid().should("exist");
    cy.wait("@listObjectsAfterFail");
      objectsGrid().should("not.contain", fileName);
    });
  });

  // Generated by Cypress Author on 2026-10-08
  it("chooses tile view → images show WebP thumbnails and other files show placeholders", () => {
    cy.uniqueRecordName("tiles").then((marker) => {
      const image = namedFixture(DOWNLOAD_SOURCE, marker);
      const note = {
        contents: Cypress.Buffer.from("storage notes"),
        fileName: `notes-${marker}.txt`,
        mimeType: "text/plain",
      };
      const thumbnailJobId = "11111111-1111-4111-8111-111111111111";
      const thumbnailPath = "/__cypress/thumbnail.webp";

      signInAndOpenDrive();
      cy.get("[aria-label='Search storage objects']").then(($search) => {
        const search = $search[0];
        if (!search) {
          throw new Error("search field is missing");
        }
        cy.get("[data-cy='dStorage_toolbar']").should(($toolbar) => {
          const toolbar = $toolbar[0];
          if (!toolbar) {
            throw new Error("storage toolbar is missing");
          }
          expect(
            toolbar.getBoundingClientRect().top,
            "toolbar sits below the search field",
          ).to.be.greaterThan(search.getBoundingClientRect().bottom - 1);
        });
      });
      cy.get("[data-cy='dStorage_toolbar']").within(() => {
        cy.get("[data-cy='dStorage_upload']").should("be.visible");
        cy.get("[data-cy='dStorage_delete_selected']").should("be.visible");
        cy.get("[aria-label='Columns']").should("be.visible");
        cy.get("[data-cy='dStorage_view_options']").should("be.visible");
      });

      uploadThroughDialog([image, note]);

      cy.intercept("GET", thumbnailPath, {
        statusCode: 200,
        headers: { "content-type": "image/webp" },
        body: "thumbnail",
      });
      cy.intercept("POST", "/api/images/transform", (req) => {
        const body: unknown = req.body;
        if (!isRecord(body) || typeof body.sourceKey !== "string") {
          throw new Error("thumbnail request is missing a source");
        }
        expect(body).to.include({
          width: 512,
          height: 320,
          fit: "cover",
          format: "webp",
          quality: 80,
        });
        expect(body.preview).to.be.oneOf(["image", "pdf", "video", "animation"]);
        expect(body.sourceKey).not.to.include(note.fileName);
        const header = req.headers["idempotency-key"];
        const idempotencyKey = Array.isArray(header) ? header[0] : header;
        expect(idempotencyKey).to.match(
          new RegExp(
            `^thumb:[0-9a-f-]{36}:${String(body.preview)}:512x320:cover:webp:80$`,
            "i",
          ),
        );
        if (body.sourceKey.includes(image.fileName)) {
          expect(body.preview).to.eq("image");
        }
        req.reply({
          statusCode: 202,
          body: { jobId: thumbnailJobId, status: "pending" },
        });
      }).as("transformImage");
      cy.intercept("GET", `/api/jobs/${thumbnailJobId}`, {
        statusCode: 200,
        body: {
          jobId: thumbnailJobId,
          status: "completed",
          httpStatus: 200,
          result: {
            url: `${Cypress.config("baseUrl")}${thumbnailPath}`,
            contentType: "image/webp",
          },
        },
      });

      cy.get("[data-cy='dStorage_view_options']").click();
      cy.get("[data-cy='dStorage_view_tiles']").click();

      objectsGrid().should("contain", image.fileName);
      cy.contains("[data-cy='dStorage_item']", note.fileName)
        .find("[data-cy='dStorage_thumbnail_fallback']")
        .should("be.visible");
      cy.contains("[data-cy='dStorage_item']", note.fileName)
        .find("[data-cy='dStorage_thumbnail_image']")
        .should("not.exist");

      cy.contains("[data-cy='dStorage_item']", image.fileName).scrollIntoView();
      cy.wait("@transformImage", { timeout: 20000 });
      cy.get("@transformImage.all", { timeout: 20000 }).should(function (
        interceptions: ReadonlyArray<{ request: { body?: unknown } }>,
      ) {
        const sourceKeys = interceptions.map(function (interception) {
          const body: unknown = interception.request.body;
          if (!isRecord(body) || typeof body.sourceKey !== "string") {
            throw new Error("thumbnail request is missing a source");
          }
          return body.sourceKey;
        });
        expect(
          sourceKeys.some(function (sourceKey) {
            return sourceKey.includes(image.fileName);
          }),
          "uploaded image requests a thumbnail",
        ).to.eq(true);
        expect(
          sourceKeys.some(function (sourceKey) {
            return sourceKey.includes(note.fileName);
          }),
          "text files do not request a thumbnail",
        ).to.eq(false);
      });
      cy.contains("[data-cy='dStorage_item']", image.fileName)
        .find("[data-cy='dStorage_thumbnail_image']")
        .should("have.attr", "src")
        .and("include", thumbnailPath);

      objectsGrid().should(($grid) => {
        const grid = $grid[0];
        if (!grid) {
          throw new Error("tile grid is missing");
        }
        expect(getComputedStyle(grid).display).to.eq("grid");
        expect(tileColumnCount(grid), "narrow tile columns").to.eq(1);
      });
      cy.viewport(1440, 900);
      objectsGrid().should(($grid) => {
        const grid = $grid[0];
        if (!grid) {
          throw new Error("tile grid is missing");
        }
        expect(tileColumnCount(grid), "wide tile columns").to.be.greaterThan(1);
      });

      cy.contains("[data-cy='dStorage_item']", image.fileName).click();
      cy.get("[data-cy='dStorage_selected_count']").should("contain", "1 selected");
      cy.contains("[data-cy='dStorage_item']", image.fileName)
        .find(`button[aria-label="Actions for ${image.fileName}"]`)
        .click();
      cy.get("[data-cy='dStorage_download']").should("be.visible");
      cy.get("body").type("{esc}");

      cy.reload();
      cy.waitForClerkLoaded();
      objectsGrid().should("contain", note.fileName);
      cy.get("[data-cy='dStorage_thumbnail_fallback']").should("be.visible");

      cy.get("[data-cy='dStorage_view_options']").click();
      cy.get("[data-cy='dStorage_view_detailed']").click();
      cy.get("[data-cy='dStorage_thumbnail']").should("not.exist");
      objectsGrid().should("contain", image.fileName);
    });
  });

  // Generated by Cypress Author on 2026-10-08
  it("chooses tile view → PDF and video show posters and a hovered video plays", () => {
    cy.uniqueRecordName("preview").then((marker) => {
      const video = namedFixture(TEST_FILES[0], marker);
      const pdf = {
        contents: Cypress.Buffer.from(
          "%PDF-1.1\n1 0 obj<<>>endobj\ntrailer<<>>\n%%EOF\n",
        ),
        fileName: `brief-${marker}.pdf`,
        mimeType: "application/pdf",
      };
      const posterJobId = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
      const animationJobId = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";
      const posterPath = "/__cypress/video-poster.webp";
      const animationPath = "/__cypress/video-animation.webp";
      let animationStage: "frames" | "encoding" | "done" = "frames";

      signInAndOpenDrive();
      uploadThroughDialog([video, pdf]);

      cy.intercept("GET", posterPath, {
        statusCode: 200,
        headers: { "content-type": "image/webp" },
        body: "poster",
      });
      cy.intercept("GET", animationPath, {
        statusCode: 200,
        headers: { "content-type": "image/webp" },
        body: "animation",
      });
      cy.intercept("POST", "/api/images/transform", (req) => {
        const body: unknown = req.body;
        if (!isRecord(body) || typeof body.preview !== "string") {
          throw new Error("thumbnail request is missing a preview");
        }
        if (typeof body.sourceKey !== "string") {
          throw new Error("thumbnail request is missing a source");
        }
        const owned =
          body.sourceKey.includes(video.fileName) ||
          body.sourceKey.includes(pdf.fileName);
        if (!owned) {
          req.reply({
            statusCode: 202,
            body: { jobId: posterJobId, status: "pending" },
          });
          return;
        }
        expect(body).to.include({
          width: 512,
          height: 320,
          fit: "cover",
          format: "webp",
          quality: 80,
        });
        const header = req.headers["idempotency-key"];
        const idempotencyKey = Array.isArray(header) ? header[0] : header;
        expect(idempotencyKey).to.match(
          new RegExp(
            `^thumb:[0-9a-f-]{36}:${body.preview}:512x320:cover:webp:80$`,
            "i",
          ),
        );
        if (body.preview === "pdf") {
          expect(body.sourceKey).to.include(pdf.fileName);
          req.reply({ statusCode: 500, body: { message: "preview failed" } });
          return;
        }
        if (body.preview === "video") {
          expect(body.sourceKey).to.include(video.fileName);
        } else if (body.preview === "animation") {
          expect(body.sourceKey).to.include(video.fileName);
        } else {
          throw new Error(`unexpected preview ${body.preview}`);
        }
        const jobId = body.preview === "animation" ? animationJobId : posterJobId;
        req.reply({
          statusCode: 202,
          body: { jobId, status: "pending" },
        });
      }).as("transformPreview");
      cy.intercept("GET", new RegExp(`/api/jobs/(${posterJobId}|${animationJobId})$`), (req) => {
        const jobId = req.url.split("/").pop();
        if (jobId === animationJobId && animationStage === "frames") {
          req.reply({
            statusCode: 200,
            body: {
              jobId,
              status: "running",
              progress: { phase: "frames", completed: 3, total: 7 },
            },
          });
          return;
        }
        if (jobId === animationJobId && animationStage === "encoding") {
          req.reply({
            statusCode: 200,
            body: {
              jobId,
              status: "running",
              progress: { phase: "encoding", completed: 7, total: 7 },
            },
          });
          return;
        }
        const path = jobId === animationJobId ? animationPath : posterPath;
        req.reply({
          statusCode: 200,
          body: {
            jobId,
            status: "completed",
            httpStatus: 200,
            result: {
              url: `${Cypress.config("baseUrl")}${path}`,
              contentType: "image/webp",
            },
          },
        });
      });

      cy.get("[data-cy='dStorage_view_options']").click();
      cy.get("[data-cy='dStorage_view_tiles']").click();
      cy.contains("[data-cy='dStorage_item']", video.fileName).scrollIntoView();
      cy.contains("[data-cy='dStorage_item']", pdf.fileName).scrollIntoView();

      cy.contains("[data-cy='dStorage_item']", pdf.fileName)
        .find("[data-cy='dStorage_thumbnail_fallback']", { timeout: 20000 })
        .should("contain", "PDF");
      cy.contains("[data-cy='dStorage_item']", pdf.fileName)
        .find("[data-cy='dStorage_thumbnail_image']")
        .should("not.exist");
      cy.contains("[data-cy='dStorage_item']", video.fileName)
        .find("[data-cy='dStorage_thumbnail_image']", { timeout: 20000 })
        .should("have.attr", "src")
        .and("include", posterPath);
      cy.contains("[data-cy='dStorage_item']", video.fileName)
        .find("[role='progressbar']")
        .should("not.exist");
      cy.get("@transformPreview.all").should(function (interceptions) {
        expect(
          previewRequests(interceptions, "animation", video.fileName),
        ).to.have.length(0);
        expect(
          previewRequests(interceptions, "video", video.fileName).length,
        ).to.be.greaterThan(0);
        expect(
          previewRequests(interceptions, "pdf", pdf.fileName).length,
        ).to.be.greaterThan(0);
      });

      cy.contains("[data-cy='dStorage_item']", video.fileName).trigger("pointerenter");
      cy.contains("[data-cy='dStorage_item']", video.fileName)
        .find("[role='progressbar']", { timeout: 20000 })
        .should("have.attr", "aria-valuenow", "3")
        .and("have.attr", "aria-valuemin", "0")
        .and("have.attr", "aria-valuemax", "7")
        .and("have.attr", "aria-label", `Generating animated preview for ${video.fileName}`);
      cy.contains("[data-cy='dStorage_item']", video.fileName)
        .find("[data-cy='dStorage_thumbnail_image']")
        .should("be.visible");
      cy.contains("[data-cy='dStorage_item']", video.fileName).trigger("pointerleave");
      cy.contains("[data-cy='dStorage_item']", video.fileName)
        .find("[role='progressbar']")
        .should("have.attr", "aria-valuenow", "3");
      cy.then(() => {
        animationStage = "encoding";
      });
      cy.contains("[data-cy='dStorage_item']", video.fileName)
        .find("[role='progressbar']", { timeout: 20000 })
        .should("have.attr", "aria-valuenow", "7");
      cy.then(() => {
        animationStage = "done";
      });
      cy.contains("[data-cy='dStorage_item']", video.fileName)
        .find("[role='progressbar']", { timeout: 20000 })
        .should("not.exist");
      cy.contains("[data-cy='dStorage_item']", video.fileName).trigger("pointerenter");
      cy.contains("[data-cy='dStorage_item']", video.fileName)
        .find("[data-cy='dStorage_thumbnail_animation']", { timeout: 20000 })
        .should("have.attr", "src")
        .and("include", animationPath);
      cy.contains("[data-cy='dStorage_item']", video.fileName)
        .find("[role='progressbar']")
        .should("not.exist");
      cy.contains("[data-cy='dStorage_item']", video.fileName).trigger("pointerleave");
      cy.contains("[data-cy='dStorage_item']", video.fileName)
        .find("[data-cy='dStorage_thumbnail_image']")
        .should("have.attr", "src")
        .and("include", posterPath);

      cy.contains("[data-cy='dStorage_item']", video.fileName).focus();
      cy.contains("[data-cy='dStorage_item']", video.fileName)
        .find("[data-cy='dStorage_thumbnail_animation']")
        .should("be.visible");
      cy.contains("[data-cy='dStorage_item']", video.fileName).trigger("pointerleave");
      cy.get("@transformPreview.all").should(function (interceptions) {
        expect(
          previewRequests(interceptions, "animation", video.fileName),
          "hover and focus share one animation",
        ).to.have.length(1);
      });
    });
  });
});
