// Generated by Cypress Author on 2026-09-16

import { isRecord } from "../tasks/narrow.js";
import { rememberPreparedObject } from "../support/preparedObject.js";

// Ordered smallest to largest so a failing upload pins down the size threshold.
const TEST_FILES = [
  "cypress/fixtures/testFiles/WIN_20251119_00_55_14_Pro.mp4",
  "cypress/fixtures/testFiles/WIN_20260102_21_30_21_Pro.jpg",
  "cypress/fixtures/testFiles/WIN_20260203_23_03_27_Pro.jpg",
  "cypress/fixtures/testFiles/WIN_20251119_00_55_32_Pro.mp4",
] as const;

const DOWNLOAD_SOURCE =
  "cypress/fixtures/testFiles/WIN_20260102_21_30_21_Pro.jpg";

function fileNameOf(path: string) {
  return path.slice(path.lastIndexOf("/") + 1);
}

function uploadedName(file: Cypress.FileReference): string {
  if (typeof file === "string") {
    return fileNameOf(file);
  }
  if (
    typeof file === "object" &&
    file !== null &&
    "fileName" in file &&
    typeof file.fileName === "string" &&
    file.fileName.length > 0
  ) {
    return file.fileName;
  }
  throw new Error("uploaded fixture is missing a file name");
}

function namedFixture(
  path: string,
  marker: string,
): { contents: string; fileName: string } {
  const base = fileNameOf(path);
  const dot = base.lastIndexOf(".");
  const stem = dot >= 0 ? base.slice(0, dot) : base;
  const ext = dot >= 0 ? base.slice(dot) : "";
  return { contents: path, fileName: `${stem}-${marker}${ext}` };
}

function objectsGrid() {
  return cy.get("[data-cy='dStorage_objects']:visible", { timeout: 20000 });
}

function signInAndOpenDrive() {
  cy.signInAsUser(0);

  cy.intercept({
    method: "GET",
    url: /\/api\/storage\/buckets\/[^/]+\/objects\?/,
  }).as("listObjects");
  // Register once per visit so later waits cannot match an earlier upload.
  cy.intercept({
    method: "POST",
    url: /\/api\/storage\/buckets\/[^/]+\/objects\/presign(\?|$)/,
  }).as("presignObject");
  cy.intercept({
    method: "POST",
    url: /\/api\/storage\/buckets\/[^/]+\/objects\/commit$/,
  }).as("commitObject");

  cy.visit("/drive/mine");
  cy.waitForClerkLoaded();
  objectsGrid().should("exist");
  cy.wait("@listObjects");
}

function fillUploadDialog(files: ReadonlyArray<Cypress.FileReference>) {
  cy.get("[data-cy='dStorage_upload']").click();
  cy.get("[role='dialog'] input[type='file']").selectFile([...files], {
    force: true,
  });
  cy.get("[data-cy='dStorage_upload_submit']").click();
}

function rememberPresign() {
  cy.wait("@presignObject", { timeout: 60000 }).then((interception) => {
    expect(interception.response?.statusCode).to.eq(200);
    return rememberPreparedObject(interception.response?.body);
  });
}

function uploadThroughDialog(files: readonly Cypress.FileReference[]) {
  fillUploadDialog(files);

  // Direct-to-S3: small presign, then the browser PUTs the bytes.
  // Commits run only after every PUT in the batch has finished.
  for (let i = 0; i < files.length; i++) {
    rememberPresign();
  }
  for (let i = 0; i < files.length; i++) {
    cy.wait("@commitObject", { timeout: 60000 })
      .its("response.statusCode")
      .should("eq", 204);
  }

  cy.get("[role='dialog']", { timeout: 20000 }).should("not.exist");
  // Wait for the list refetch before reading a row.
  cy.wait("@listObjects", { timeout: 20000 });

  for (const file of files) {
    objectsGrid().should("contain", uploadedName(file));
  }
}

describe("drive", () => {
  beforeEach(() => {
    cy.viewport("iphone-6");
  });

  it("uploads each test file one at a time → each name appears in the storage table", () => {
    cy.uniqueRecordName("one").then((marker) => {
      signInAndOpenDrive();

      for (const path of TEST_FILES) {
        uploadThroughDialog([namedFixture(path, marker)]);
      }
    });
  });

  // Generated by Cypress Author on 2026-10-06
  // The four size boundaries are covered one at a time. The batch only needs
  // two small fixtures so the largest file is not transferred twice.
  it("uploads two small files together → both names appear in the storage table", () => {
    cy.uniqueRecordName("batch").then((marker) => {
      signInAndOpenDrive();
      uploadThroughDialog(TEST_FILES.slice(0, 2).map((path) => namedFixture(path, marker)));
    });
  });

  it("downloads a stored file from the row actions menu → saved bytes match the original", () => {
    cy.uniqueRecordName("download").then((marker) => {
      const file = namedFixture(DOWNLOAD_SOURCE, marker);

      signInAndOpenDrive();
      uploadThroughDialog([file]);

    cy.intercept({
      method: "GET",
      url: /\/api\/storage\/buckets\/[^/]+\/objects\/download/,
    }).as("downloadObject");

      objectsGrid()
        .contains("[data-cy='dStorage_item']", file.fileName)
        .find(`button[aria-label="Actions for ${file.fileName}"]`)
        .click();
      cy.get("[data-cy='dStorage_download']").click();

      cy.wait("@downloadObject", { timeout: 20000 })
        .its("response.statusCode")
        .should("eq", 200);

      cy.readFile(DOWNLOAD_SOURCE, null).then((expected) => {
        cy.readFile(
          `${Cypress.config("downloadsFolder")}/${file.fileName}`,
          null,
          { timeout: 20000 },
        ).should((actual) => {
          expect(
            Cypress.Buffer.from(actual).equals(Cypress.Buffer.from(expected)),
            "downloaded bytes match the original",
          ).to.eq(true);
        });
      });
    });
  });

  // Generated by Cypress Author on 2026-09-17
  it("S3 upload fails → the object is not committed and does not appear in the storage table", () => {
    cy.uniqueRecordName("fail").then((marker) => {
      const fileName = `upload-should-not-commit-${marker}.jpg`;
      const failedPutPath = "/__cypress_s3_put_fail";

      signInAndOpenDrive();

    cy.intercept({
      method: "POST",
      url: /\/api\/storage\/buckets\/[^/]+\/objects\/abort$/,
    }).as("abortObject");
    // Last-defined route wins: prepare still runs, then the PUT target is
    // rewritten to a same-origin stub so this never depends on AWS hostnames.
    cy.intercept(
      {
        method: "POST",
        url: /\/api\/storage\/buckets\/[^/]+\/objects\/presign(\?|$)/,
      },
      (req) => {
        req.continue((res) => {
          const body: unknown = res.body;
          if (isRecord(body)) {
            body.url = `${Cypress.config("baseUrl")}${failedPutPath}`;
          }
        });
      },
    ).as("presignObject");
    cy.intercept(
      { method: "PUT", url: `**${failedPutPath}` },
      { statusCode: 500, body: "forced upload failure" },
    ).as("s3PutFailed");

    fillUploadDialog([
      {
        contents: DOWNLOAD_SOURCE,
        fileName,
        mimeType: "image/jpeg",
      },
    ]);

      cy.wait("@presignObject", { timeout: 60000 }).then((interception) => {
        expect(interception.response?.statusCode).to.eq(200);
        return rememberPreparedObject(interception.response?.body);
      });
    cy.wait("@s3PutFailed", { timeout: 60000 })
      .its("response.statusCode")
      .should("eq", 500);
    cy.wait("@abortObject", { timeout: 60000 })
      .its("response.statusCode")
      .should("eq", 204);
    cy.get("@commitObject.all").should("have.length", 0);

    cy.get("[data-cy='dStorage_upload_error']").should("be.visible");
    cy.get("[role='dialog']").should("exist");

    cy.intercept({
      method: "GET",
      url: /\/api\/storage\/buckets\/[^/]+\/objects\?/,
    }).as("listObjectsAfterFail");
    cy.visit("/drive/mine");
    cy.waitForClerkLoaded();
    objectsGrid().should("exist");
    cy.wait("@listObjectsAfterFail");
      objectsGrid().should("not.contain", fileName);
    });
  });
});
