// Generated by Cypress Author on 2026-09-16

// Ordered smallest to largest so a failing upload pins down the size threshold.
const TEST_FILES = [
  "cypress/fixtures/testFiles/WIN_20251119_00_55_14_Pro.mp4",
  "cypress/fixtures/testFiles/WIN_20260102_21_30_21_Pro.jpg",
  "cypress/fixtures/testFiles/WIN_20260203_23_03_27_Pro.jpg",
  "cypress/fixtures/testFiles/WIN_20251119_00_55_32_Pro.mp4",
] as const;

const DOWNLOAD_SOURCE =
  "cypress/fixtures/testFiles/WIN_20260102_21_30_21_Pro.jpg";

function fileNameOf(path: string) {
  return path.slice(path.lastIndexOf("/") + 1);
}

function objectsGrid() {
  return cy.get("[data-cy='dStorage_objects']:visible", { timeout: 20000 });
}

function signInAndOpenDrive() {
  cy.signInAsUser(0);

  cy.clerkLoaded();
  cy.window().should((win) => {
    expect(win.Clerk.user).to.not.equal(null);
  });

  cy.intercept({
    method: "GET",
    url: /\/api\/storage\/buckets\/[^/]+\/objects\?/,
  }).as("listObjects");
  // Register once per visit so later waits cannot match an earlier upload.
  cy.intercept({
    method: "POST",
    url: /\/api\/storage\/buckets\/[^/]+\/objects\/presign(\?|$)/,
  }).as("presignObject");
  cy.intercept({
    method: "POST",
    url: /\/api\/storage\/buckets\/[^/]+\/objects\/commit$/,
  }).as("commitObject");

  cy.visit("/drive/mine");
  cy.waitForClerkLoaded();
  objectsGrid().should("exist");
  cy.wait("@listObjects");
}

function uploadThroughDialog(paths: readonly string[]) {
  cy.get("[data-cy='dStorage_upload']").click();
  cy.get("[role='dialog'] input[type='file']").selectFile([...paths], {
    force: true,
  });
  cy.get("[data-cy='dStorage_upload_submit']").click();

  // Direct-to-S3: small presign, then the browser PUTs the bytes.
  // Commits run only after every PUT in the batch has finished.
  for (let i = 0; i < paths.length; i++) {
    cy.wait("@presignObject", { timeout: 60000 })
      .its("response.statusCode")
      .should("eq", 200);
  }
  for (let i = 0; i < paths.length; i++) {
    cy.wait("@commitObject", { timeout: 60000 })
      .its("response.statusCode")
      .should("eq", 204);
  }

  cy.get("[role='dialog']", { timeout: 20000 }).should("not.exist");
  // Same-name overwrites keep the label in the grid, so wait for the list
  // refetch before reading a row; otherwise download still has the old key.
  cy.wait("@listObjects", { timeout: 20000 });

  for (const path of paths) {
    objectsGrid().should("contain", fileNameOf(path));
  }
}

describe("drive", () => {
  let skipRemaining = false;

  before(() => {
    cy.task("supabaseDbReset");
    cy.task("emptyBucket");
  });

  beforeEach(function () {
    if (skipRemaining) {
      throw new Error("An earlier test in this spec failed");
    }
  });

  afterEach(function () {
    if (this.currentTest?.state === "failed") {
      skipRemaining = true;
    }
  });

  it("uploads each test file one at a time → each name appears in the storage table", () => {
    signInAndOpenDrive();

    for (const path of TEST_FILES) {
      uploadThroughDialog([path]);
    }
  });

  it("uploads all test files together → every name appears in the storage table", () => {
    signInAndOpenDrive();
    uploadThroughDialog(TEST_FILES);
  });

  it("downloads a stored file from the row actions menu → saved bytes match the original", () => {
    const fileName = fileNameOf(DOWNLOAD_SOURCE);

    signInAndOpenDrive();
    uploadThroughDialog([DOWNLOAD_SOURCE]);

    cy.intercept({
      method: "GET",
      url: /\/api\/storage\/buckets\/[^/]+\/objects\/download/,
    }).as("downloadObject");

    objectsGrid()
      .contains("[data-cy='dStorage_item']", fileName)
      .find(`button[aria-label="Actions for ${fileName}"]`)
      .click();
    cy.get("[data-cy='dStorage_download']").click();

    cy.wait("@downloadObject", { timeout: 20000 })
      .its("response.statusCode")
      .should("eq", 200);

    cy.readFile(DOWNLOAD_SOURCE, null).then((expected) => {
      cy.readFile(`${Cypress.config("downloadsFolder")}/${fileName}`, null, {
        timeout: 20000,
      }).should((actual) => {
        expect(
          Cypress.Buffer.from(actual).equals(Cypress.Buffer.from(expected)),
          "downloaded bytes match the original",
        ).to.eq(true);
      });
    });
  });
});
