function ownerId() {
  return cy
    .env<{ test_users: [Cypress.TestUser, Cypress.TestUser] }>(["test_users"])
    .then(({ test_users }) => {
      const owner = test_users[0];
      if (!owner) {
        throw new Error("test_users[0] is missing");
      }
      return owner.user_id;
    });
}

describe("instagreg", () => {
  beforeEach(() => {
    cy.viewport("iphone-6");
  });

  // Generated by Cypress Author on 2026-10-06
  it("creates a post → the new text appears in the list", () => {
    cy.uniqueRecordName("post").then((postText) => {
      cy.signInAsUser(0);

      cy.intercept("POST", "/api/views/igPosts/new/item").as("createPost");
      cy.intercept("GET", "/api/views/igPosts/list/get").as("listGet");

      cy.visit("/instagreg");
      cy.waitForClerkLoaded();
      cy.get("[data-cy='igPosts_list']", { timeout: 20000 }).should("exist");
      cy.wait("@listGet");

      cy.intercept("GET", "/api/views/igPosts/list/get").as("listRefetch");

      cy.get("[data-cy='p_text_content_field'] > input", {
        timeout: 20000,
      }).type(postText);
      cy.get("[data-cy='create_ig_post_submit']").click();

      cy.wait("@createPost").its("response.statusCode").should("eq", 202);
      cy.wait("@listRefetch");

      cy.get("[data-cy='igPosts_list']", { timeout: 20000 }).should(
        "contain",
        postText,
      );
    });
  });

  // Generated by Cypress Author on 2026-10-06
  it("edits a seeded post → the list shows the updated heading", () => {
    cy.uniqueRecordName("post").then((postText) => {
      ownerId().then((identifier) => {
        cy.task("createIgPostAsUser", {
          identifier,
          p_text_content: postText,
          p_public: true,
        });
      });

      cy.signInAsUser(0);
      cy.intercept("PATCH", "/api/views/igPosts/one/patch").as("updatePost");
      cy.visit("/instagreg");

      cy.contains("[data-cy='igPosts_list'] article", postText, {
        timeout: 20000,
      })
        .find("[data-cy='ig_post_actions']")
        .click();

      cy.get("[data-cy='ig_post_edit']").click();

      cy.get("[data-cy='edit_p_text_content_field'] textarea")
        .should("have.value", postText)
        .clear()
        .type(`## ${postText}`);

      cy.get("[data-cy='edit_ig_post_submit']").click();

      cy.wait("@updatePost").its("response.statusCode").should("eq", 202);

      cy.get("[data-cy='ig_post_body'] h2", { timeout: 20000 }).should(
        "contain",
        postText,
      );
    });
  });

  // Generated by Cypress Author on 2026-10-06
  it("another user opens the feed → a seeded public post is visible", () => {
    cy.uniqueRecordName("post").then((postText) => {
      ownerId().then((identifier) => {
        cy.task("createIgPostAsUser", {
          identifier,
          p_text_content: postText,
          p_public: true,
        });
      });

      cy.signInAsUser(1);
      cy.visit("/instagreg");

      cy.get("[data-cy='igPosts_list']", { timeout: 20000 }).should(
        "contain",
        postText,
      );
    });
  });

  // Generated by Cypress Author on 2026-10-06
  it("another user is viewing the feed → a newly seeded public post appears", () => {
    cy.uniqueRecordName("live").then((liveText) => {
      cy.signInAsUser(1);

      cy.intercept("GET", "/api/views/igPosts/list/get").as("listGet");

      cy.visit("/instagreg");
      cy.waitForClerkLoaded();
      cy.get("[data-cy='igPosts_list']", { timeout: 20000 }).should("exist");
      cy.wait("@listGet").its("response.statusCode").should("eq", 202);
      cy.get("[data-cy='mqtt_connected']", { timeout: 20000 }).should("exist");

      ownerId().then((identifier) => {
        cy.task("createIgPostAsUser", {
          identifier,
          p_text_content: liveText,
          p_public: true,
        })
          .its("post_id")
          .should("be.a", "string");
      });

      cy.get("[data-cy='igPosts_list']", { timeout: 20000 }).should(
        "contain",
        liveText,
      );
      cy.location("pathname").should("include", "instagreg");
    });
  });
});
