// Generated by Cypress Author on 2026-09-15
// Shape of get_tds_todos_tree: root nodes with recursively nested children.
interface TodoTreeNode {
  todo_item_id: string;
  title: string;
  todo_item_parent_id: string | null;
  children: TodoTreeNode[] | null;
}

// React Aria walks drop targets one at a time (before / on / after per row), so
// a handful of presses is always enough for a two row tree.
const MAX_DROP_TARGET_STEPS = 12;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function firstTodoSpaceId(body: unknown): string {
  if (!Array.isArray(body) || !isRecord(body[0])) {
    throw new Error("create_tds_todo_space returned no todo_space_id");
  }
  const todoSpaceId = body[0].todo_space_id;
  if (typeof todoSpaceId !== "string" || todoSpaceId.length === 0) {
    throw new Error("create_tds_todo_space returned no todo_space_id");
  }
  return todoSpaceId;
}

function isTodoTreeNode(value: unknown): value is TodoTreeNode {
  if (!isRecord(value)) {
    return false;
  }
  if (typeof value.todo_item_id !== "string" || typeof value.title !== "string") {
    return false;
  }
  if (
    value.todo_item_parent_id !== null &&
    typeof value.todo_item_parent_id !== "string"
  ) {
    return false;
  }
  if (value.children === null) {
    return true;
  }
  return Array.isArray(value.children) && value.children.every(isTodoTreeNode);
}

function todoTree(body: unknown): TodoTreeNode[] {
  if (!Array.isArray(body) || !body.every(isTodoTreeNode)) {
    throw new Error("todo tree response was not a tree");
  }
  return body;
}

// React Aria's DragManager listens for keydown and keyup on document in the
// capture phase, so keyboard drag and drop can be driven from body regardless of
// where focus currently sits.
function triggerDragKey(type: "keydown" | "keyup", key: string) {
  cy.get("body").trigger(type, {
    key,
    eventConstructor: "KeyboardEvent",
    force: true,
  });
}

// Only the row itself carries [data-drop-target] for dropPosition "on"; the
// "before" and "after" positions render a separate DropIndicator element. So
// finding the target row marked means the next Enter nests instead of reorders.
function seekOnDropTarget(title: string, step = 0) {
  cy.get("[data-drop-target]").then(($target) => {
    const onRow = $target.filter("[data-cy='tdsTodos_item']");
    if (onRow.length === 1 && onRow.text().includes(title)) {
      return;
    }

    if (step >= MAX_DROP_TARGET_STEPS) {
      throw new Error(
        `no "on" drop target for "${title}" after ${step} ArrowDown presses`,
      );
    }

    const previous = $target.get(0);
    triggerDragKey("keydown", "ArrowDown");
    // Waiting for the marker to move off the previous element flushes React's
    // render before the next read, so the loop cannot overshoot the target.
    cy.get("[data-drop-target]").should(($next) => {
      expect($next.get(0), "drop target moved").to.not.equal(previous);
    });

    seekOnDropTarget(title, step + 1);
  });
}

function ownerId(index: 0 | 1) {
  return cy
    .env<{ test_users: [Cypress.TestUser, Cypress.TestUser] }>(["test_users"])
    .then(({ test_users }) => {
      const owner = test_users[index];
      if (!owner) {
        throw new Error(`test_users[${index}] is missing`);
      }
      return owner.user_id;
    });
}

function openTodoSpace(todoSpaceId: string) {
  cy.intercept("GET", "/api/views/tdsTodos/*/tree/get").as("treeLoad");
  cy.visit(`/todos/space/${todoSpaceId}`);
  cy.waitForClerkLoaded();
  cy.get("[data-cy='tdsTodos_tree']", { timeout: 20000 }).should("exist");
  cy.wait("@treeLoad");
  // Neither todo mutation invalidates the tree query, so MQTT is the only thing
  // that can refresh it. Gate on a live subscription before mutating anything.
  cy.get("[data-cy='mqtt_connected']", { timeout: 20000 }).should("exist");
}

function createTodoThroughDialog(title: string) {
  cy.get("[data-cy='new_tds_todo_button']").click();
  cy.get("[data-cy='p_title_field'] > input").type(title);
  cy.get("[data-cy='create_tds_todo_submit']").click();

  cy.wait("@createTodo").then((interception) => {
    expect(interception.response?.statusCode).to.eq(200);
  });
  // The mutation's onSuccess closes the dialog.
  cy.get("[data-cy='p_title_field']").should("not.exist");
}

describe("todos", () => {
  beforeEach(() => {
    cy.viewport("iphone-6");
  });

  it("creates a todo space → the list shows it and the space page opens", () => {
    cy.uniqueRecordName("space").then((spaceName) => {
      cy.signInAsUser(0);

      cy.intercept("POST", "/api/views/tdsTodoSpaces/new/item").as(
        "createSpace",
      );
      cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listGet");

      cy.visit("/todos");
      // Generated by Cypress Author on 2026-09-15
      // Session validation on / does not cover /todos. After visit, Clerk.loaded
      // is still false and the list GET can finish after requestTimeout (5000ms).
      cy.waitForClerkLoaded();
      cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
        "exist",
      );
      cy.wait("@listGet");
      cy.get("[data-cy='mqtt_connected']", { timeout: 20000 }).should("exist");

      cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listRefetch");

      cy.get("[data-cy='p_name_field'] > input", { timeout: 20000 }).type(
        spaceName,
      );
      cy.get("[data-cy='create_tds_todo_space_submit']").click();

      cy.wait("@createSpace").then((interception) => {
        expect(interception.response?.statusCode).to.eq(200);
        const todoSpaceId = firstTodoSpaceId(interception.response?.body);
        cy.wrap(todoSpaceId).as("todoSpaceId");
      });

      cy.wait("@listRefetch");
      cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
        "contain",
        spaceName,
      );

      cy.contains("[data-cy='tdsTodoSpaces_item']", spaceName)
        .find("[data-cy='ig_post_body']")
        .click();

      cy.get<string>("@todoSpaceId").then((todoSpaceId) => {
        cy.location("pathname").should("eq", `/todos/space/${todoSpaceId}`);
        cy.contains("h2", todoSpaceId).should("exist");
      });
    });
  });

  // Generated by Cypress Author on 2026-10-06
  it("creates a todo in a seeded space → the tree live-updates over MQTT", () => {
    cy.uniqueRecordName("todo").then((marker) => {
      const seeded = [0, 1, 2, 3].map((index) => `${marker}-seed-${index}`);
      const created = `${marker}-created`;

      cy.signInAsUser(0);
      ownerId(0).then((identifier) => {
        cy.task("createTdsTodosAsUser", {
          identifier,
          p_name: marker,
          p_public: false,
          todos: seeded.map((p_title) => ({
            p_title,
            p_description: "",
          })),
        }).then(({ todo_space_id }) => {
          cy.intercept("POST", "/api/views/tdsTodos/*/new/post").as(
            "createTodo",
          );
          openTodoSpace(todo_space_id);
          // Registered after the subscription is live so the initial load,
          // already waited on above, is excluded from this refetch.
          cy.intercept("GET", "/api/views/tdsTodos/*/tree/get").as(
            "treeRefetch",
          );

          createTodoThroughDialog(created);
          cy.wait("@treeRefetch");

          // get_tds_todos_tree orders roots by created_at DESC, so the todo
          // created in the dialog is first and the seeded siblings follow.
          const newestFirst = [created, ...seeded.slice().reverse()];
          cy.get("[data-cy='tdsTodos_item']").should(($rows) => {
            expect($rows).to.have.length(newestFirst.length);
            newestFirst.forEach((title, index) => {
              expect(
                $rows.eq(index).attr("aria-level"),
                `row ${index} level`,
              ).to.eq("1");
              expect($rows.eq(index).text(), `row ${index} title`).to.contain(
                title,
              );
            });
          });
        });
      });
    });
  });

  // Generated by Cypress Author on 2026-10-06
  it("drags a todo onto a sibling → ancestry is corrected over MQTT", () => {
    cy.uniqueRecordName("drag").then((marker) => {
      const parentTitle = `${marker}-parent`;
      const draggedTitle = `${marker}-dragged`;

      cy.signInAsUser(0);
      ownerId(0).then((identifier) => {
        // Seed the dragged todo last so it is the newer root, in row one,
        // directly above its soon-to-be parent.
        cy.task("createTdsTodosAsUser", {
          identifier,
          p_name: marker,
          p_public: false,
          todos: [
            { p_title: parentTitle, p_description: "" },
            { p_title: draggedTitle, p_description: "" },
          ],
        }).then(({ todo_space_id }) => {
          openTodoSpace(todo_space_id);
          cy.get("[data-cy='tdsTodos_item']").should("have.length", 2);

          cy.intercept("PATCH", "/api/views/tdsTodos/*/tree/move/patch").as(
            "moveTodos",
          );
          // Re-aliased so the wait below can only match the refetch caused by the move.
          cy.intercept("GET", "/api/views/tdsTodos/*/tree/get").as(
            "moveRefetch",
          );

          // Enter React Aria's keyboard drag mode from the row's grip affordance.
          cy.contains("[data-cy='tdsTodos_item']", draggedTitle)
            .find("[data-cy='tree_item_drag_handle']")
            .focus()
            .type("{enter}");
          cy.contains("[data-cy='tdsTodos_item']", draggedTitle).should(
            "have.attr",
            "data-dragging",
            "true",
          );

          seekOnDropTarget(parentTitle);
          // DragManager drops on keyup, not keydown.
          triggerDragKey("keyup", "Enter");

          cy.wait("@moveTodos").then((interception) => {
            expect(interception.response?.statusCode).to.eq(200);
          });

          // persistMove never refetches, so this GET can only have been triggered by
          // the MQTT message from the tds_todo_item_data insert. That makes it the
          // authoritative server state rather than the optimistic client move.
          cy.wait("@moveRefetch").then((interception) => {
            const roots = todoTree(interception.response?.body);
            expect(roots.map((node) => node.title)).to.not.include(
              draggedTitle,
            );

            const parent = roots.find((node) => node.title === parentTitle);
            expect(parent, `root "${parentTitle}"`).to.not.be.undefined;

            const children = parent?.children ?? [];
            expect(children.map((child) => child.title)).to.deep.eq([
              draggedTitle,
            ]);
            expect(children[0]?.todo_item_parent_id).to.eq(parent?.todo_item_id);
          });

          cy.contains("[data-cy='tdsTodos_item']", parentTitle).should(
            "have.attr",
            "data-has-child-items",
          );
          // RACMovableTree rebuilds the tree on every refetch, so expansion state
          // after the MQTT correction is not guaranteed.
          cy.contains("[data-cy='tdsTodos_item']", parentTitle).then(($row) => {
            if ($row.attr("data-expanded") === undefined) {
              cy.wrap($row).find("[data-cy='tree_item_chevron']").click();
            }
          });

          cy.contains("[data-cy='tdsTodos_item']", draggedTitle).should(
            "have.attr",
            "aria-level",
            "2",
          );
        });
      });
    });
  });

  // Generated by Cypress Author on 2026-10-06
  it("another user opens the list → a seeded private space is hidden", () => {
    cy.uniqueRecordName("private").then((spaceName) => {
      ownerId(0).then((identifier) => {
        cy.task("createTdsTodoSpaceAsUser", {
          identifier,
          p_name: spaceName,
          p_public: false,
        });
      });

      cy.signInAsUser(1);
      cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listGet");
      cy.visit("/todos");
      cy.waitForClerkLoaded();
      cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
        "exist",
      );
      cy.wait("@listGet");
      cy.get("[data-cy='tdsTodoSpaces_list']").should("not.contain", spaceName);
    });
  });

  // Generated by Cypress Author on 2026-10-06
  it("a private space is created for someone else → the signed-in list refreshes only for the following public space", () => {
    cy.uniqueRecordName("mqtt").then((marker) => {
      const privateName = `${marker}-private`;
      const publicName = `${marker}-public`;

      cy.signInAsUser(0);
      cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listGet");
      cy.visit("/todos");
      cy.waitForClerkLoaded();
      cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
        "exist",
      );
      cy.wait("@listGet");
      cy.get("[data-cy='mqtt_connected']", { timeout: 20000 }).should("exist");

      // Capture only refetches after MQTT is connected; the initial list GET
      // is already waited on. Private notifies the owner only. The public
      // space is the observable control that the notify path has finished.
      cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listRefetch");

      ownerId(1).then((identifier) => {
        cy.task("createTdsTodoSpaceAsUser", {
          identifier,
          p_name: privateName,
          p_public: false,
        }).then(() => {
          cy.task("createTdsTodoSpaceAsUser", {
            identifier,
            p_name: publicName,
            p_public: true,
          });
        });
      });

      cy.wait("@listRefetch").its("response.statusCode").should("eq", 200);
      cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 })
        .should("contain", publicName)
        .and("not.contain", privateName);
      cy.get("@listRefetch.all").should("have.length", 1);
    });
  });
});
