const spaceName = `space-${Date.now()}`;

describe("todos", () => {
  before(() => {
    cy.task("supabaseDbReset");
  });

  beforeEach(() => {
    cy.viewport("iphone-6");
  });

  it("creates a todo space, shows it in the list, and opens the space page", () => {
    cy.signInAsUser(0);

    cy.clerkLoaded();
    cy.window().should((win) => {
      expect(win.Clerk.user).to.not.equal(null);
    });

    cy.intercept("POST", "/api/views/tdsTodoSpaces/new/item").as("createSpace");
    cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listGet");

    cy.visit("/todos");
    // Generated by Cypress Author on 2026-09-15
    // clerkLoaded() on / does not cover /todos. After visit, Clerk.loaded is
    // still false and the list GET can finish after requestTimeout (5000ms).
    cy.waitForClerkLoaded();
    cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
      "exist",
    );
    cy.wait("@listGet");
    cy.get("[data-cy='mqtt_connected']", { timeout: 20000 }).should("exist");

    cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listRefetch");

    cy.get("[data-cy='p_name_field'] > input", { timeout: 20000 }).type(
      spaceName,
    );
    cy.get("[data-cy='create_tds_todo_space_submit']").click();

    cy.wait("@createSpace").then((interception) => {
      expect(interception.response?.statusCode).to.eq(200);
      const todoSpaceId = interception.response?.body?.[0]?.todo_space_id as
        | string
        | undefined;
      if (!todoSpaceId) {
        throw new Error("create_tds_todo_space returned no todo_space_id");
      }
      cy.wrap(todoSpaceId).as("todoSpaceId");
    });

    cy.wait("@listRefetch");
    cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
      "contain",
      spaceName,
    );

    cy.contains("[data-cy='tdsTodoSpaces_item']", spaceName)
      .find("[data-cy='ig_post_body']")
      .click();

    cy.get<string>("@todoSpaceId").then((todoSpaceId) => {
      cy.location("pathname").should("eq", `/todos/space/${todoSpaceId}`);
      cy.contains("h2", todoSpaceId).should("exist");
    });
  });

  it("another user cannot see a private todo space", () => {
    cy.signInAsUser(1);

    cy.clerkLoaded();
    cy.window().should((win) => {
      expect(win.Clerk.user).to.not.equal(null);
    });

    cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listGet");

    cy.visit("/todos");
    cy.waitForClerkLoaded();
    cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
      "exist",
    );
    cy.wait("@listGet");
    cy.get("[data-cy='tdsTodoSpaces_list']").should("not.contain", spaceName);
  });

  it("another user creates a private todo space → signed-in user's list does not live-update over MQTT", () => {
    const liveSpace = `space-${Date.now()}`;

    cy.signInAsUser(0);

    cy.clerkLoaded();
    cy.window().should((win) => {
      expect(win.Clerk.user).to.not.equal(null);
    });

    cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listGet");

    cy.visit("/todos");
    cy.waitForClerkLoaded();
    cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
      "exist",
    );
    cy.wait("@listGet");
    cy.get("[data-cy='mqtt_connected']", { timeout: 20000 }).should("exist");

    // Capture only refetches after MQTT is connected; the initial list GET is already waited on.
    cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listRefetch");

    cy.env<{ test_users: [Cypress.TestUser, Cypress.TestUser] }>([
      "test_users",
    ]).then(({ test_users }) => {
      const actor = test_users[1];
      if (!actor) {
        throw new Error("test_users[1] is missing");
      }
      cy.task("createTdsTodoSpaceAsUser", {
        identifier: actor.user_id,
        p_name: liveSpace,
        p_public: false,
      });
    });

    cy.get("[data-cy='tdsTodoSpaces_list']").should("not.contain", liveSpace);

    // Bound the "no MQTT refetch" check to the same window cy.wait("@alias") uses.
    const requestTimeout = Cypress.config("requestTimeout");
    cy.wait(requestTimeout);
    cy.get("@listRefetch.all").should("have.length", 0);
  });
});
