const spaceName = `space-${Date.now()}`;

// Generated by Cypress Author on 2026-09-15
// Shape of get_tds_todos_tree: root nodes with recursively nested children.
interface TodoTreeNode {
  todo_item_id: string;
  title: string;
  todo_item_parent_id: string | null;
  children: TodoTreeNode[] | null;
}

// React Aria walks drop targets one at a time (before / on / after per row), so
// a handful of presses is always enough for a two row tree.
const MAX_DROP_TARGET_STEPS = 12;

// React Aria's DragManager listens for keydown and keyup on document in the
// capture phase, so keyboard drag and drop can be driven from body regardless of
// where focus currently sits.
function triggerDragKey(type: "keydown" | "keyup", key: string) {
  cy.get("body").trigger(type, {
    key,
    eventConstructor: "KeyboardEvent",
    force: true,
  });
}

// Only the row itself carries [data-drop-target] for dropPosition "on"; the
// "before" and "after" positions render a separate DropIndicator element. So
// finding the target row marked means the next Enter nests instead of reorders.
function seekOnDropTarget(title: string, step = 0) {
  cy.get("[data-drop-target]").then(($target) => {
    const onRow = $target.filter("[data-cy='tdsTodos_item']");
    if (onRow.length === 1 && onRow.text().includes(title)) {
      return;
    }

    if (step >= MAX_DROP_TARGET_STEPS) {
      throw new Error(
        `no "on" drop target for "${title}" after ${step} ArrowDown presses`,
      );
    }

    const previous = $target.get(0);
    triggerDragKey("keydown", "ArrowDown");
    // Waiting for the marker to move off the previous element flushes React's
    // render before the next read, so the loop cannot overshoot the target.
    cy.get("[data-drop-target]").should(($next) => {
      expect($next.get(0), "drop target moved").to.not.equal(previous);
    });

    seekOnDropTarget(title, step + 1);
  });
}

function openSeededTodoSpace() {
  cy.intercept("GET", "/api/views/tdsTodos/*/tree/get").as("treeLoad");

  cy.env<{ test_users: [Cypress.TestUser, Cypress.TestUser] }>(["test_users"])
    .then(({ test_users }) => {
      const owner = test_users[0];
      if (!owner) {
        throw new Error("test_users[0] is missing");
      }
      // Seed via the RPC; the todo space creation UI is already covered by the
      // first test in this spec.
      return cy.task("createTdsTodoSpaceAsUser", {
        identifier: owner.user_id,
        p_name: `todo-space-${Date.now()}`,
        p_public: false,
      });
    })
    .then(({ todo_space_id }) => {
      cy.visit(`/todos/space/${todo_space_id}`);
    });

  cy.waitForClerkLoaded();
  cy.get("[data-cy='tdsTodos_tree']", { timeout: 20000 }).should("exist");
  cy.wait("@treeLoad");
  // Neither todo mutation invalidates the tree query, so MQTT is the only thing
  // that can refresh it. Gate on a live subscription before mutating anything.
  cy.get("[data-cy='mqtt_connected']", { timeout: 20000 }).should("exist");
}

function createTodoThroughDialog(title: string) {
  cy.get("[data-cy='new_tds_todo_button']").click();
  cy.get("[data-cy='p_title_field'] > input").type(title);
  cy.get("[data-cy='create_tds_todo_submit']").click();

  cy.wait("@createTodo").then((interception) => {
    expect(interception.response?.statusCode).to.eq(200);
  });
  // The mutation's onSuccess closes the dialog.
  cy.get("[data-cy='p_title_field']").should("not.exist");
}

describe("todos", () => {
  before(() => {
    cy.task("supabaseDbReset");
  });

  beforeEach(() => {
    cy.viewport("iphone-6");
  });

  it("creates a todo space, shows it in the list, and opens the space page", () => {
    cy.signInAsUser(0);

    cy.clerkLoaded();
    cy.window().should((win) => {
      expect(win.Clerk.user).to.not.equal(null);
    });

    cy.intercept("POST", "/api/views/tdsTodoSpaces/new/item").as("createSpace");
    cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listGet");

    cy.visit("/todos");
    // Generated by Cypress Author on 2026-09-15
    // clerkLoaded() on / does not cover /todos. After visit, Clerk.loaded is
    // still false and the list GET can finish after requestTimeout (5000ms).
    cy.waitForClerkLoaded();
    cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
      "exist",
    );
    cy.wait("@listGet");
    cy.get("[data-cy='mqtt_connected']", { timeout: 20000 }).should("exist");

    cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listRefetch");

    cy.get("[data-cy='p_name_field'] > input", { timeout: 20000 }).type(
      spaceName,
    );
    cy.get("[data-cy='create_tds_todo_space_submit']").click();

    cy.wait("@createSpace").then((interception) => {
      expect(interception.response?.statusCode).to.eq(200);
      const todoSpaceId = interception.response?.body?.[0]?.todo_space_id as
        | string
        | undefined;
      if (!todoSpaceId) {
        throw new Error("create_tds_todo_space returned no todo_space_id");
      }
      cy.wrap(todoSpaceId).as("todoSpaceId");
    });

    cy.wait("@listRefetch");
    cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
      "contain",
      spaceName,
    );

    cy.contains("[data-cy='tdsTodoSpaces_item']", spaceName)
      .find("[data-cy='ig_post_body']")
      .click();

    cy.get<string>("@todoSpaceId").then((todoSpaceId) => {
      cy.location("pathname").should("eq", `/todos/space/${todoSpaceId}`);
      cy.contains("h2", todoSpaceId).should("exist");
    });
  });

  // Generated by Cypress Author on 2026-09-15
  it("creates five todos in a space → tree live-updates over MQTT", () => {
    const stamp = Date.now();
    const titles = Array.from(
      { length: 5 },
      (_, index) => `todo-${stamp}-${index}`,
    );

    cy.signInAsUser(0);

    cy.clerkLoaded();
    cy.window().should((win) => {
      expect(win.Clerk.user).to.not.equal(null);
    });

    cy.intercept("POST", "/api/views/tdsTodos/*/new/post").as("createTodo");

    openSeededTodoSpace();

    // Registered after the subscription is live so the initial load, already
    // waited on above, is excluded from these refetches.
    cy.intercept("GET", "/api/views/tdsTodos/*/tree/get").as("treeRefetch");

    for (const title of titles) {
      createTodoThroughDialog(title);
      cy.wait("@treeRefetch");
      cy.get("[data-cy='tdsTodos_tree']", { timeout: 20000 }).should(
        "contain",
        title,
      );
    }

    // get_tds_todos_tree orders roots by created_at DESC, so newest first.
    const newestFirst = [...titles].reverse();
    cy.get("[data-cy='tdsTodos_item']").should(($rows) => {
      expect($rows).to.have.length(titles.length);
      newestFirst.forEach((title, index) => {
        expect($rows.eq(index).attr("aria-level"), `row ${index} level`).to.eq(
          "1",
        );
        expect($rows.eq(index).text(), `row ${index} title`).to.contain(title);
      });
    });
  });

  // Generated by Cypress Author on 2026-09-15
  it("drags a todo onto a sibling → ancestry is corrected over MQTT", () => {
    const stamp = Date.now();
    const parentTitle = `parent-${stamp}`;
    const draggedTitle = `dragged-${stamp}`;

    cy.signInAsUser(0);

    cy.clerkLoaded();
    cy.window().should((win) => {
      expect(win.Clerk.user).to.not.equal(null);
    });

    cy.intercept("POST", "/api/views/tdsTodos/*/new/post").as("createTodo");

    openSeededTodoSpace();

    cy.intercept("GET", "/api/views/tdsTodos/*/tree/get").as("treeRefetch");

    // Roots sort newest first, so creating the dragged todo last puts it in row
    // one, directly above its soon to be parent.
    for (const title of [parentTitle, draggedTitle]) {
      createTodoThroughDialog(title);
      cy.wait("@treeRefetch");
      cy.get("[data-cy='tdsTodos_tree']", { timeout: 20000 }).should(
        "contain",
        title,
      );
    }
    cy.get("[data-cy='tdsTodos_item']").should("have.length", 2);

    cy.intercept("PATCH", "/api/views/tdsTodos/*/tree/move/patch").as(
      "moveTodos",
    );
    // Re-aliased so the wait below can only match the refetch caused by the move.
    cy.intercept("GET", "/api/views/tdsTodos/*/tree/get").as("moveRefetch");

    // Enter React Aria's keyboard drag mode from the row's grip affordance.
    cy.contains("[data-cy='tdsTodos_item']", draggedTitle)
      .find("[data-cy='tree_item_drag_handle']")
      .focus()
      .type("{enter}");
    cy.contains("[data-cy='tdsTodos_item']", draggedTitle).should(
      "have.attr",
      "data-dragging",
      "true",
    );

    seekOnDropTarget(parentTitle);
    // DragManager drops on keyup, not keydown.
    triggerDragKey("keyup", "Enter");

    cy.wait("@moveTodos").then((interception) => {
      expect(interception.response?.statusCode).to.eq(200);
    });

    // persistMove never refetches, so this GET can only have been triggered by
    // the MQTT message from the tds_todo_item_data insert. That makes it the
    // authoritative server state rather than the optimistic client move.
    cy.wait("@moveRefetch").then((interception) => {
      const roots = (interception.response?.body ?? []) as TodoTreeNode[];
      expect(roots, "tree roots").to.be.an("array");
      expect(roots.map((node) => node.title)).to.not.include(draggedTitle);

      const parent = roots.find((node) => node.title === parentTitle);
      expect(parent, `root "${parentTitle}"`).to.not.be.undefined;

      const children = parent?.children ?? [];
      expect(children.map((child) => child.title)).to.deep.eq([draggedTitle]);
      expect(children[0]?.todo_item_parent_id).to.eq(parent?.todo_item_id);
    });

    cy.contains("[data-cy='tdsTodos_item']", parentTitle).should(
      "have.attr",
      "data-has-child-items",
    );
    // RACMovableTree rebuilds the tree on every refetch, so expansion state
    // after the MQTT correction is not guaranteed.
    cy.contains("[data-cy='tdsTodos_item']", parentTitle).then(($row) => {
      if ($row.attr("data-expanded") === undefined) {
        cy.wrap($row).find("[data-cy='tree_item_chevron']").click();
      }
    });

    cy.contains("[data-cy='tdsTodos_item']", draggedTitle).should(
      "have.attr",
      "aria-level",
      "2",
    );
  });

  it("another user cannot see a private todo space", () => {
    cy.signInAsUser(1);

    cy.clerkLoaded();
    cy.window().should((win) => {
      expect(win.Clerk.user).to.not.equal(null);
    });

    cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listGet");

    cy.visit("/todos");
    cy.waitForClerkLoaded();
    cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
      "exist",
    );
    cy.wait("@listGet");
    cy.get("[data-cy='tdsTodoSpaces_list']").should("not.contain", spaceName);
  });

  it("another user creates a private todo space → signed-in user's list does not live-update over MQTT", () => {
    const liveSpace = `space-${Date.now()}`;

    cy.signInAsUser(0);

    cy.clerkLoaded();
    cy.window().should((win) => {
      expect(win.Clerk.user).to.not.equal(null);
    });

    cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listGet");

    cy.visit("/todos");
    cy.waitForClerkLoaded();
    cy.get("[data-cy='tdsTodoSpaces_list']", { timeout: 20000 }).should(
      "exist",
    );
    cy.wait("@listGet");
    cy.get("[data-cy='mqtt_connected']", { timeout: 20000 }).should("exist");

    // Capture only refetches after MQTT is connected; the initial list GET is already waited on.
    cy.intercept("GET", "/api/views/tdsTodoSpaces/list/get").as("listRefetch");

    cy.env<{ test_users: [Cypress.TestUser, Cypress.TestUser] }>([
      "test_users",
    ]).then(({ test_users }) => {
      const actor = test_users[1];
      if (!actor) {
        throw new Error("test_users[1] is missing");
      }
      cy.task("createTdsTodoSpaceAsUser", {
        identifier: actor.user_id,
        p_name: liveSpace,
        p_public: false,
      });
    });

    cy.get("[data-cy='tdsTodoSpaces_list']").should("not.contain", liveSpace);

    // Bound the "no MQTT refetch" check to the same window cy.wait("@alias") uses.
    const requestTimeout = Cypress.config("requestTimeout");
    cy.wait(requestTimeout);
    cy.get("@listRefetch.all").should("have.length", 0);
  });
});
