/// <reference types="cypress" />
/// <reference path="./index.d.ts" />

import { addClerkCommands } from "@clerk/testing/cypress";

addClerkCommands({ Cypress, cy });

Cypress.on("uncaught:exception", (err) => {
  if (err.message.includes("reading 'id'")) {
    return false;
  }
});

// Cypress 16 removed Cypress.env(). @clerk/testing's setupClerkTestingToken
// still calls it for CLERK_FAPI / CLERK_TESTING_TOKEN, so we inject the
// testing token with cy.env() instead of the official helper.
function setupClerkTestingToken(
  frontendApi: string,
  testingToken: string | undefined,
) {
  const fapiUrl = frontendApi.replace(/index\./, "");

  // Cypress 16 visit() on http origins follows redirects in Cypress, not the
  // browser, so this intercept never sees /v1/client/handshake. It still
  // attaches the token to Clerk JS XHR after the document loads.
  cy.intercept(`https://${fapiUrl}/v1/**`, (req) => {
    if (testingToken) {
      req.query.__clerk_testing_token = testingToken;
    }
    req.continue();
  });
}

// clerk-js DevBrowser.setup() POSTs /v1/dev_browser and stores body.id in
// __clerk_db_jwt. Seeding that cookie before visit stops clerkMiddleware
// from 307ing to handshake (which cy.visit follows until maxRedirects).
function seedClerkDevBrowser(
  frontendApi: string,
  testingToken: string | undefined,
) {
  const fapiUrl = frontendApi.replace(/index\./, "");

  cy.request({
    method: "POST",
    url: `https://${fapiUrl}/v1/dev_browser`,
    qs: testingToken ? { __clerk_testing_token: testingToken } : {},
    failOnStatusCode: false,
  }).then((res) => {
    const id =
      res.body &&
      typeof res.body === "object" &&
      "id" in res.body &&
      typeof res.body.id === "string"
        ? res.body.id
        : undefined;

    if (id) {
      cy.setCookie("__clerk_db_jwt", id, { path: "/", sameSite: "lax" });
    }
  });
}

// Generated by Cypress Author on 2026-09-14
// clerkLoaded() retries only for defaultCommandTimeout (4000ms). After a
// full page visit Clerk exists immediately but loaded stays false until
// FAPI finishes, which can take longer on heavier routes.
Cypress.Commands.add("waitForClerkLoaded", function () {
  cy.window({ timeout: 20000 }).should((win) => {
    expect(win).to.not.have.property("Clerk", undefined);
    expect(win.Clerk.loaded).to.eq(true);
  });
});

Cypress.Commands.add("signInAsUser", function (user: 0 | 1) {
  cy.env<{
    test_users: [Cypress.TestUser, Cypress.TestUser];
    CLERK_FAPI: string;
    CLERK_TESTING_TOKEN: string | undefined;
  }>(["test_users", "CLERK_FAPI", "CLERK_TESTING_TOKEN"]).then(
    ({ test_users, CLERK_FAPI, CLERK_TESTING_TOKEN }) => {
      const { user_id } = test_users[user];

      setupClerkTestingToken(CLERK_FAPI, CLERK_TESTING_TOKEN);
      seedClerkDevBrowser(CLERK_FAPI, CLERK_TESTING_TOKEN);

      cy.task("createClerkSignInToken", user_id).then((ticket) => {
        cy.visit("/");
        // visit() only waits for the document load event. Clerk.loaded stays
        // false until FAPI /v1/client finishes, which exceeds the 4s default.
        cy.waitForClerkLoaded();
        cy.window().should((win) => {
          expect(win.Clerk.client).to.exist;
        });

        cy.window().then(async (win) => {
          if (win.Clerk.user) {
            await win.Clerk.signOut();
          }

          const signIn = win.Clerk.client?.signIn;
          if (!signIn) {
            throw new Error("Clerk.client.signIn is not available");
          }

          const result = await signIn.create({
            strategy: "ticket",
            ticket,
          });

          if (result.status !== "complete" || !result.createdSessionId) {
            throw new Error(
              `Clerk ticket sign-in incomplete (status=${result.status})`,
            );
          }

          await win.Clerk.setActive({ session: result.createdSessionId });
        });

        cy.window().should((win) => {
          expect(win.Clerk.user).to.not.equal(null);
        });

        cy.window().then((win) => {
          const session = win.Clerk.session;
          if (!session) {
            throw new Error("Clerk session missing after sign-in");
          }
          return session.getToken().then((token) => {
            cy.wrap(token).as("clerkToken");
          });
        });
      });
    },
  );
});

export {};
